/* Personnages, studios, auteurs, compositeurs — réponse en texte libre. */
export const HEROES = [
['char','Batman|Bruce Wayne',1939,'Comics|Super-héros','Bob Kane|Bill Finger','DC Comics',0,[
 'Personnage de bande dessinée américaine, apparu en 1939.',
 'Un milliardaire orphelin qui refuse d’utiliser une arme à feu.',
 'Publié par l’éditeur new-yorkais concurrent de Marvel.',
 'Sa ville est corrompue, gothique, et porte un nom de ville imaginaire du New Jersey.',
 'Un signal projeté sur les nuages sert à l’appeler depuis le toit d’un commissariat.'],
 'Bill Finger a inventé le costume, le nom Gotham et l’identité de Bruce Wayne, mais n’a été crédité officiellement qu’en 2015, cinquante ans après sa mort.',
 ['Superman','Le Joker','Robin']],
['char','Dark Vador|Darth Vader|Anakin Skywalker',1977,'Science-fiction|Cinéma','George Lucas|James Earl Jones|David Prowse','Lucasfilm',0,[
 'Personnage de cinéma apparu en 1977, devenu l’archétype du méchant moderne.',
 'Une armure noire, une respiration mécanique, un empire galactique à faire régner.',
 'Trois personnes différentes lui prêtent corps, voix et souffle.',
 'Son casque s’inspire du kabuto des samouraïs japonais.',
 'La révélation de sa paternité, au deuxième film, a été gardée secrète même de l’acteur du fils.'],
 'La réplique de la révélation était fausse pendant le tournage : l’équipe croyait tourner une autre phrase. Seuls Lucas et le réalisateur connaissaient la vraie.',
 ['Luke Skywalker','L’Empereur','Star Wars']],
['char','Ellen Ripley|Ripley',1979,'Science-fiction|Cinéma','Ridley Scott|Sigourney Weaver|Dan O’Bannon','20th Century Fox',0,[
 'Personnage de cinéma né en 1979, dans un film d’horreur spatiale.',
 'Officier de bord promue héroïne par élimination de tout l’équipage.',
 'Le rôle avait été écrit pour un homme et n’a été féminisé qu’au dernier moment.',
 'Elle revient dans trois suites, dont une réalisée par James Cameron.',
 'Elle affronte la reine de l’espèce à bord d’un chargeur d’exosquelette industriel.'],
 'Le scénario original précisait que tous les personnages étaient unisexes et pouvaient être joués indifféremment. C’est cette note qui a rendu le rôle possible.',
 ['Alien','Sarah Connor']],
['char','Tyler Durden',1996,'Littérature|Cinéma','Chuck Palahniuk|David Fincher|Brad Pitt','20th Century Fox',0,[
 'Personnage né dans un roman de 1996, popularisé par son adaptation trois ans plus tard.',
 'Fabricant de savon le jour, fondateur d’un club clandestin la nuit.',
 'Il n’existe pas vraiment, et le récit ne le dit qu’aux trois quarts.',
 'Le romancier a écrit le livre pendant ses pauses de mécanicien poids lourds.',
 'Son projet final, baptisé Chaos, vise les sièges des sociétés de cartes de crédit.'],
 'Le savon qu’il vend est fabriqué à partir de graisse humaine volée dans les poubelles d’une clinique de liposuccion — détail conservé du roman.',
 ['Fight Club','Le narrateur']],
['char','Hannibal Lecter',1981,'Littérature|Cinéma','Thomas Harris|Anthony Hopkins','Orion Pictures',0,[
 'Personnage de roman apparu en 1981, incarné à l’écran par plusieurs acteurs.',
 'Psychiatre de renom, esthète, doté d’un odorat et d’une mémoire hors norme.',
 'L’acteur qui l’a rendu célèbre n’apparaît que seize minutes dans le film oscarisé.',
 'Il aide le FBI depuis sa cellule, en échange d’informations intimes.',
 'Il porte un masque facial lors de ses transferts, à cause d’un incident avec une infirmière.'],
 'Anthony Hopkins a construit le personnage en refusant de cligner des yeux, et en s’inspirant de la voix de HAL 9000 dans 2001.',
 ['Le Silence des agneaux','Clarice Starling']],
['char','Neo|Thomas Anderson',1999,'Science-fiction|Cinéma','Lana Wachowski|Lilly Wachowski|Keanu Reeves','Warner Bros.',0,[
 'Personnage de cinéma apparu en 1999, programmeur le jour, pirate la nuit.',
 'Son nom d’état civil et son pseudonyme sont l’anagramme l’un de l’autre… presque.',
 'Il apprend le kung-fu par téléchargement direct dans le cerveau.',
 'On lui annonce qu’il est l’Élu, ce qu’il refuse de croire pendant deux films.',
 'Il esquive des balles en se cambrant en arrière sur un toit d’immeuble.'],
 'Keanu Reeves a tourné une partie des combats avec une minerve, à la suite d’une opération des cervicales subie juste avant le tournage.',
 ['Matrix','Morpheus','Trinity']],
['char','Walter White|Heisenberg',2008,'Télévision|Drame','Vince Gilligan|Bryan Cranston','AMC',0,[
 'Personnage de série américaine créé en 2008.',
 'Professeur de chimie de lycée, diagnostiqué d’un cancer du poumon inopérable.',
 'Son créateur voulait transformer monsieur Tout-le-monde en Scarface.',
 'Il choisit comme pseudonyme le nom d’un physicien allemand du principe d’incertitude.',
 'Son produit est reconnaissable à sa teinte bleue, obtenue par une synthèse sans pseudoéphédrine.'],
 'Bryan Cranston a demandé que le personnage porte des sous-vêtements couleur chair précise, pour que sa nudité au premier épisode soit gênante plutôt que comique.',
 ['Breaking Bad','Jesse Pinkman','Saul Goodman']],
['char','Gandalf',1937,'Fantasy|Littérature','J. R. R. Tolkien|Ian McKellen','Allen & Unwin',0,[
 'Personnage littéraire apparu en 1937 dans un roman pour enfants.',
 'Un magicien errant, l’un des cinq envoyés en Terre du Milieu.',
 'Il change de couleur entre le premier et le deuxième volet de la trilogie.',
 'Son interprète au cinéma a tourné la plupart de ses scènes séparé de ses partenaires, pour l’échelle.',
 'Il barre le passage d’un démon de flamme sur un pont de pierre étroit.'],
 'Ian McKellen a pleuré de frustration en tournant les scènes de Fondcombe : seul devant des écrans verts, il ne voyait aucun de ses partenaires.',
 ['Le Seigneur des anneaux','Frodon','Saroumane']],
['char','Indiana Jones|Henry Jones Jr',1981,'Aventure|Cinéma','George Lucas|Steven Spielberg|Harrison Ford','Lucasfilm',0,[
 'Personnage de cinéma apparu en 1981, archéologue de terrain très peu académique.',
 'Chapeau en feutre, fouet, veste de cuir, et une peur irrationnelle des serpents.',
 'Créé par le duo derrière Star Wars et Les Dents de la mer.',
 'Il enseigne à l’université entre deux pillages de tombeaux.',
 'Une scène de duel au sabre a été remplacée par un coup de revolver, l’acteur étant malade ce jour-là.'],
 'La scène du sabre du Caire devait durer plusieurs minutes. Harrison Ford, souffrant de dysenterie, a proposé d’abréger : Spielberg a accepté sur-le-champ.',
 ['Lara Croft','Han Solo']],
['char','Sherlock Holmes',1887,'Policier|Littérature','Arthur Conan Doyle','Ward Lock & Co',0,[
 'Personnage littéraire apparu en 1887, sans doute le plus adapté de l’histoire.',
 'Londres victorien, un violon, une adresse de Baker Street.',
 'Son auteur l’a tué en 1893, puis a dû le ressusciter sous la pression du public.',
 'Il pratique une méthode qu’il nomme déduction, mais qui relève surtout de l’induction.',
 'Son adversaire le plus célèbre est un professeur de mathématiques.'],
 'Conan Doyle trouvait son personnage encombrant et considérait ses romans historiques comme son vrai travail. Personne ne les lit plus.',
 ['Hercule Poirot','Watson','Moriarty']],
['char','James Bond|007',1953,'Espionnage|Littérature|Cinéma','Ian Fleming|Sean Connery','Eon Productions',0,[
 'Personnage né dans un roman de 1953, porté à l’écran depuis 1962.',
 'Un agent britannique autorisé à tuer, amateur de cocktails mal préparés.',
 'Son auteur travaillait au renseignement naval pendant la guerre.',
 'Sept acteurs principaux se sont succédé, dont un seul pour un unique film.',
 'Son numéro matricule contient deux zéros et un sept.'],
 'Fleming a pris le nom dans un guide ornithologique : James Bond était un vrai ornithologue américain, spécialiste des oiseaux des Caraïbes.',
 ['Ethan Hunt','Jason Bourne']],
['char','Lara Croft',1996,'Jeu vidéo|Aventure','Toby Gard|Core Design','Eidos',0,[
 'Personnage de jeu vidéo apparu en 1996, sur console 32 bits et PC.',
 'Aristocrate britannique et archéologue, elle explore des tombeaux oubliés.',
 'Créée par un studio anglais de Derby.',
 'Elle a été jouée au cinéma par Angelina Jolie puis Alicia Vikander.',
 'Ses proportions initiales résultent en partie d’un réglage laissé par erreur à 150 %.'],
 'Le personnage devait à l’origine être un aventurier masculin trop proche d’Indiana Jones. Le changement de sexe visait à éviter le procès.',
 ['Tomb Raider','Indiana Jones']],
['char','Link',1986,'Jeu vidéo|Aventure','Shigeru Miyamoto|Takashi Tezuka','Nintendo',0,[
 'Personnage de jeu vidéo apparu en 1986, muet dans presque tous ses jeux.',
 'Vêtu de vert, il traverse un royaume nommé Hyrule.',
 'Il n’est pas le personnage-titre de sa propre série, contrairement à ce qu’on croit souvent.',
 'Il est gaucher dans la plupart des épisodes, sauf dans une version inversée par miroir.',
 'Son nom vient de l’idée qu’il relie le passé et le futur du royaume.'],
 'Beaucoup pensent que le personnage s’appelle du nom de la série. La princesse, elle, tient son nom de l’épouse de Francis Scott Fitzgerald.',
 ['Zelda','Ocarina of Time','Ganondorf']],
['char','Samus Aran',1986,'Jeu vidéo|Science-fiction','Nintendo R&D1|Hiroji Kiyotake','Nintendo',0,[
 'Personnage de jeu vidéo apparu en 1986, dans un jeu d’exploration spatiale.',
 'Chasseuse de primes en armure orange, elle se roule en boule pour passer les conduits.',
 'Sa série a donné son nom à la moitié d’un genre entier.',
 'On ne découvre son identité qu’en terminant le jeu assez vite.',
 'Elle affronte un organisme parasite énergivore dont sa série tire son nom.'],
 'Révéler qu’une héroïne se cachait sous l’armure était en 1986 une surprise si rare que la presse japonaise en a fait un événement.',
 ['Metroid','Ripley']],
['char','Geralt de Riv|Geralt',1986,'Fantasy|Littérature|Jeu vidéo','Andrzej Sapkowski|Doug Cockle|Henry Cavill','CD Projekt Red',0,[
 'Personnage créé en 1986 dans une nouvelle polonaise, popularisé bien plus tard.',
 'Mutant entraîné dès l’enfance, il est payé pour tuer des créatures.',
 'Adapté en jeux vidéo par un studio de Varsovie, puis en série télévisée.',
 'Ses yeux jaunes et ses cheveux blancs sont les séquelles des mutations.',
 'Il porte deux épées : une en acier, une en argent.'],
 'La légende des deux épées, une pour les hommes une pour les monstres, vient des jeux : dans les romans, l’argent sert simplement contre certaines créatures.',
 ['The Witcher 3','Ciri','Yennefer']],
['char','Kratos',2005,'Jeu vidéo|Mythologie','David Jaffe|Christopher Judge|Terrence Carson','Santa Monica Studio',0,[
 'Personnage de jeu vidéo apparu en 2005, à la peau cendreuse.',
 'Ancien général spartiate, il détruit méthodiquement un panthéon entier.',
 'Sa série a changé de mythologie en 2018 pour aller vers le Nord.',
 'Sa pâleur vient des cendres de sa famille, collées à sa peau par une malédiction.',
 'Ses armes de départ sont deux lames enchaînées à ses avant-bras.'],
 'Dans le redémarrage de 2018, le personnage cache ses lames sous terre pour tenter d’être un meilleur père. Il finit par les déterrer.',
 ['God of War','Atreus']],
['char','Spider-Man|Peter Parker',1962,'Comics|Super-héros','Stan Lee|Steve Ditko','Marvel Comics',0,[
 'Personnage de bande dessinée apparu en 1962, adolescent au moment de ses débuts.',
 'Orphelin élevé par son oncle et sa tante dans le Queens.',
 'L’éditeur avait d’abord jugé qu’un héros arachnide dégoûterait les lecteurs.',
 'Il tire ses fils grâce à des lanceurs qu’il a lui-même conçus, dans les comics.',
 'Une phrase sur le pouvoir et la responsabilité résume sa morale, prononcée par son oncle.'],
 'Le personnage a été publié dans le dernier numéro d’une revue en cours d’annulation, seul moyen pour Stan Lee de passer outre le refus de son éditeur.',
 ['Batman','Iron Man','Miles Morales']],
['char','Hermione Granger',1997,'Fantasy|Littérature','J. K. Rowling|Emma Watson','Bloomsbury',0,[
 'Personnage de roman apparu en 1997, dans le premier tome d’une série de sept.',
 'Née de parents dentistes sans pouvoirs magiques.',
 'Elle est la meilleure élève de sa promotion et fait respecter le règlement.',
 'Elle utilise un objet officiel du ministère pour suivre plus de cours que possible.',
 'Son chat s’appelle Pattenrond et n’est pas tout à fait un chat.'],
 'Le retourneur de temps a été retiré de l’intrigue par l’autrice car il rendait tous les problèmes suivants trop faciles à résoudre.',
 ['Harry Potter','Ron Weasley']],
['char','Tintin',1929,'Bande dessinée|Aventure','Hergé','Casterman',0,[
 'Personnage de bande dessinée belge apparu en 1929 dans un supplément pour la jeunesse.',
 'Reporter, il ne rédige pourtant presque jamais d’article.',
 'Son créateur signait de ses initiales inversées.',
 'Il est accompagné d’un fox-terrier blanc et d’un capitaine alcoolique.',
 'Sa mèche relevée apparaît dès le deuxième album, dans une voiture décapotable.'],
 'Le tout premier album a été renié par son auteur, qui a toujours refusé de le redessiner en couleurs, contrairement à tous les autres.',
 ['Astérix','Le capitaine Haddock']],
['char','Astérix',1959,'Bande dessinée|Humour','René Goscinny|Albert Uderzo','Dargaud',0,[
 'Personnage de bande dessinée française apparu en 1959 dans un magazine.',
 'Un village d’irréductibles résiste encore et toujours à l’envahisseur.',
 'Créé par un scénariste et un dessinateur, dont le premier est mort en 1977.',
 'Sa force vient d’une potion préparée par le druide du village.',
 'Son meilleur ami livre des menhirs et n’a pas droit à la potion.'],
 'Le nom de presque tous les personnages est un jeu de mots suffixé : le druide se termine en -ix comme les chefs gaulois attestés par César.',
 ['Tintin','Obélix','Idéfix']],
['char','Son Goku|Goku',1984,'Manga|Shonen','Akira Toriyama','Shueisha',0,[
 'Personnage de manga apparu en 1984, inspiré d’un roman chinois du XVIᵉ siècle.',
 'Enfant à queue de singe élevé par un vieil ermite dans la montagne.',
 'Sa série a été prépubliée dans le plus grand hebdomadaire de manga japonais.',
 'Il appartient à un peuple guerrier extraterrestre qui se transforme sous la pleine lune.',
 'Il concentre l’énergie de la planète entière dans une sphère levée à bout de bras.'],
 'L’auteur avait prévu d’arrêter la série bien plus tôt à plusieurs reprises ; l’éditeur l’a convaincu de continuer pendant près de dix ans.',
 ['Dragon Ball','Vegeta','Naruto']],
['char','Naruto Uzumaki|Naruto',1999,'Manga|Shonen','Masashi Kishimoto','Shueisha',0,[
 'Personnage de manga apparu en 1999, orphelin et turbulent.',
 'Un village caché de ninjas, une académie, et un rêve de devenir chef.',
 'Prépublié dans le même hebdomadaire que Dragon Ball et One Piece.',
 'Un démon renard à neuf queues est scellé dans son ventre depuis sa naissance.',
 'Sa technique de base consiste à se dédoubler en dizaines de copies solides.'],
 'L’auteur voulait initialement en faire un manga sur la cuisine ; le mot naruto désigne une tranche de pâte de poisson posée sur les ramen.',
 ['One Piece','Sasuke','Goku']],
['char','Monkey D. Luffy|Luffy',1997,'Manga|Shonen','Eiichiro Oda','Shueisha',0,[
 'Personnage de manga apparu en 1997, dans la série la plus vendue de tous les temps.',
 'Un garçon qui veut devenir roi des pirates et trouver un trésor légendaire.',
 'Son corps est élastique depuis qu’il a mangé un fruit démoniaque.',
 'Il porte un chapeau de paille prêté par un pirate qu’il admire.',
 'Il ne sait pas nager, comme tous ceux qui ont mangé ce genre de fruit.'],
 'L’auteur avait annoncé une série de cinq ans. Elle en compte plus de vingt-cinq et il maintient qu’il connaît la fin depuis le début.',
 ['Naruto','One Piece','Zoro']],
['char','Arsène Lupin',1905,'Policier|Littérature','Maurice Leblanc|Omar Sy','Je sais tout',0,[
 'Personnage littéraire français apparu en 1905 dans un magazine populaire.',
 'Cambrioleur mondain, maître du déguisement, il vole surtout les riches indélicats.',
 'Créé en réponse commerciale au succès d’un détective britannique.',
 'Une série télévisée française de 2021 l’a relancé mondialement, sans l’incarner directement.',
 'Son surnom complet ajoute deux mots : gentleman et cambrioleur.'],
 'Maurice Leblanc a fait affronter son héros à un certain Herlock Sholmès, après que les ayants droit de Conan Doyle ont protesté contre le nom d’origine.',
 ['Sherlock Holmes','Lupin']],
['char','Hercule Poirot',1920,'Policier|Littérature','Agatha Christie|David Suchet','Collins Crime Club',0,[
 'Personnage littéraire apparu en 1920, dans le premier roman de son autrice.',
 'Ancien policier belge réfugié en Angleterre pendant la Première Guerre mondiale.',
 'Il apparaît dans plus de trente romans et une cinquantaine de nouvelles.',
 'Il parle de ses petites cellules grises et déteste qu’on le croie français.',
 'Sa moustache et son obsession de la symétrie sont ses signes distinctifs.'],
 'Agatha Christie a fini par le détester et l’a tué dans un roman écrit dès les années 1940, publié seulement en 1975. Le New York Times lui a consacré une nécrologie.',
 ['Sherlock Holmes','Miss Marple']],
['char','Le Joker|Joker',1940,'Comics|Super-vilain','Bob Kane|Bill Finger|Jerry Robinson','DC Comics',0,[
 'Personnage de bande dessinée apparu en 1940, dans le premier numéro d’une série dérivée.',
 'Peau blanche, cheveux verts, sourire figé : son origine change à chaque récit.',
 'Il devait mourir dès sa première apparition ; un éditeur a exigé qu’on le garde.',
 'Trois acteurs différents ont obtenu ou été nommés à l’Oscar en l’interprétant.',
 'Son opposé porte une cape et refuse de tuer, ce qui l’exaspère.'],
 'Le personnage a été inspiré par le visage figé de Conrad Veidt dans L’Homme qui rit, film muet de 1928.',
 ['Batman','Joker']]
];

export const OTHERS = [
['studio','Studio Ghibli|Ghibli',1985,'Animation|Studio','Hayao Miyazaki|Isao Takahata|Toshio Suzuki','Tokyo',0,[
 'Studio d’animation fondé en 1985, à Tokyo.',
 'Ses films mêlent nature, enfance et machines volantes, sans manichéisme.',
 'Son nom vient d’un mot arabe désignant un vent chaud du Sahara, repris par un avion italien.',
 'Il a produit le premier film d’animation non anglophone oscarisé.',
 'Son logo montre une créature grise et ronde, née d’un film de 1988.'],
 'Le studio a longtemps refusé le numérique et payait ses animateurs au salaire fixe plutôt qu’à l’image, contre l’usage de toute l’industrie japonaise.',
 ['Hayao Miyazaki','Le Voyage de Chihiro']],
['studio','Pixar',1986,'Animation|Studio','John Lasseter|Ed Catmull|Steve Jobs','Emeryville',0,[
 'Studio d’animation américain devenu indépendant en 1986.',
 'Il a produit le premier long métrage entièrement en images de synthèse.',
 'Il était à l’origine une division matérielle de Lucasfilm, rachetée par Steve Jobs.',
 'Un court métrage précède systématiquement chacun de ses longs en salle.',
 'Une lampe de bureau à ressort remplace une lettre de son logo.'],
 'Steve Jobs a acheté le studio dix millions de dollars en 1986. Disney l’a racheté 7,4 milliards en 2006, faisant de Jobs son premier actionnaire.',
 ['Studio Ghibli','Toy Story']],
['studio','A24',2012,'Cinéma|Studio','Daniel Katz|David Fenkel|John Hodges','New York',0,[
 'Société de production et de distribution américaine fondée en 2012.',
 'Elle s’est imposée sur le cinéma d’auteur, l’horreur élégante et les premiers films.',
 'Son nom vient d’une autoroute italienne empruntée par l’un des fondateurs.',
 'Elle a produit Moonlight, Hérédité, Midsommar et Everything Everywhere All at Once.',
 'Son logo minimaliste est devenu un argument marketing à lui seul.'],
 'La société est devenue une marque au point que des spectateurs choisissent un film sur la seule foi de son logo — phénomène rare pour un distributeur.',
 ['Pixar']],
['studio','Nintendo',1889,'Jeu vidéo|Entreprise','Fusajiro Yamauchi|Shigeru Miyamoto|Gunpei Yokoi','Kyoto',0,[
 'Entreprise japonaise fondée en 1889, bien avant l’électronique.',
 'Elle fabriquait à l’origine des cartes à jouer peintes à la main.',
 'Elle a essayé les taxis, les hôtels et les nouilles instantanées avant le jeu vidéo.',
 'Son siège se trouve à Kyoto.',
 'Elle a relancé un marché américain effondré en 1985 avec une console 8 bits.'],
 'Avant les jeux, l’entreprise possédait une chaîne d’hôtels de passe et une société de taxis. Les deux ont échoué.',
 ['Sega','Super Mario Bros.']],
['studio','HBO',1972,'Télévision|Chaîne','Chris Albrecht|Richard Plepler','New York',0,[
 'Chaîne américaine payante lancée en 1972, sur le câble.',
 'Sans publicité et hors régulation des chaînes hertziennes, elle a pu tout montrer.',
 'Elle a produit Les Soprano, The Wire, Game of Thrones et Chernobyl.',
 'Son slogan affirmait pendant des années qu’elle n’était pas de la télévision.',
 'Son générique sonore se réduit à un grésillement suivi de trois lettres.'],
 'Son modèle payant l’a libérée des annonceurs : c’est cette liberté économique, plus que le talent, qui a rendu possible la télévision d’auteur.',
 ['Netflix','Les Soprano']],
['author','Hayao Miyazaki',1941,'Animation|Réalisateur','Studio Ghibli|Joe Hisaishi','Tokyo',0,[
 'Réalisateur japonais d’animation né en 1941.',
 'Il dessine encore lui-même une grande partie des images clés de ses films.',
 'Il a cofondé son studio en 1985 avec Isao Takahata.',
 'Il a annoncé sa retraite au moins cinq fois, sans jamais s’y tenir.',
 'Ses films reviennent obsessionnellement au vol, au vent et aux machines volantes.'],
 'Son père dirigeait une usine de pièces d’avions de chasse pendant la guerre. Le vol et la culpabilité industrielle traversent toute son œuvre.',
 ['Studio Ghibli','Le Voyage de Chihiro']],
['author','Christopher Nolan',1970,'Cinéma|Réalisateur','Emma Thomas|Hans Zimmer|Hoyte van Hoytema','Syncopy',0,[
 'Réalisateur britannico-américain né en 1970.',
 'Il tourne en pellicule, refuse le numérique et limite les effets générés par ordinateur.',
 'Il produit ses films avec son épouse depuis ses débuts.',
 'Il n’utilise ni téléphone portable ni adresse électronique, selon ses propres déclarations.',
 'Le temps, sa manipulation et sa perte irriguent presque tous ses scénarios.'],
 'Pour un film de 2020, il a acheté un vrai Boeing 747 et l’a fait exploser : cela coûtait moins cher que de le recréer numériquement.',
 ['Inception','Interstellar','Memento']],
['author','Quentin Tarantino',1963,'Cinéma|Réalisateur','Roger Avary|Uma Thurman|Samuel L. Jackson','Miramax',0,[
 'Réalisateur américain né en 1963, ancien employé de vidéoclub.',
 'Ses dialogues digressent longuement sur des sujets sans rapport avec l’intrigue.',
 'Il a annoncé qu’il arrêterait après dix films.',
 'Tous ses films partagent une marque de cigarettes et une chaîne de restauration fictives.',
 'Il a obtenu deux Oscars du scénario, en 1995 et en 2013.'],
 'Il a vendu son premier scénario, True Romance, pour financer son premier tournage. Il n’a jamais réalisé ce film, confié à Tony Scott.',
 ['Pulp Fiction','Kill Bill']],
['author','Stanley Kubrick',1928,'Cinéma|Réalisateur','Arthur C. Clarke|Jack Nicholson','Warner Bros.',0,[
 'Réalisateur américain né en 1928, mort en 1999, treize longs métrages en quarante-cinq ans.',
 'Photographe pour un magazine avant de passer au cinéma, à vingt et un ans.',
 'Il exigeait parfois plus de cent prises d’un même plan.',
 'Installé en Angleterre, il refusait l’avion et dirigeait ses tournages américains à distance.',
 'Son dernier film est sorti quatre mois après sa mort.'],
 'Pour un film de 1975, il a fait développer par la NASA un objectif ultra-lumineux afin de filmer des scènes à la seule lumière des bougies.',
 ['2001','Shining','Orange mécanique']],
['music','Hans Zimmer',1957,'Musique|Compositeur','Christopher Nolan|Denis Villeneuve|Lisa Gerrard','Remote Control',0,[
 'Compositeur allemand né en 1957, installé à Los Angeles.',
 'Il a débuté dans la pop et joué sur un tube new wave des années 1980.',
 'Il dirige un collectif de compositeurs plutôt qu’un simple studio.',
 'Il a signé les musiques de Gladiator, Interstellar, Dune et Le Roi Lion.',
 'Pour un film spatial de 2014, il a écrit d’abord pour orgue d’église.'],
 'Nolan lui avait donné une seule page racontant un père et son fils, sans mentionner l’espace. La musique a été écrite avant que le compositeur ne sache de quel film il s’agissait.',
 ['Ennio Morricone','John Williams','Interstellar']],
['music','Ennio Morricone',1928,'Musique|Compositeur','Sergio Leone|Quentin Tarantino','Rome',0,[
 'Compositeur italien né en 1928, plus de quatre cents partitions de films.',
 'Trompettiste de formation, il a longtemps arrangé de la variété sous pseudonyme.',
 'Il était camarade de classe du réalisateur avec qui il a fait ses westerns.',
 'Il n’a reçu son Oscar compétitif qu’en 2016, à quatre-vingt-sept ans.',
 'Ses partitions mêlent guitare électrique, sifflement humain et cris d’animaux.'],
 'Sur les westerns de Leone, la musique était composée avant le tournage et diffusée sur le plateau : les acteurs jouaient au rythme de la partition.',
 ['Hans Zimmer','Le Bon, la Brute et le Truand']],
['music','John Williams',1932,'Musique|Compositeur','Steven Spielberg|George Lucas','Los Angeles',0,[
 'Compositeur américain né en 1932, recordman des nominations aux Oscars parmi les vivants.',
 'Il a signé les thèmes de Star Wars, Indiana Jones, Jurassic Park et Harry Potter.',
 'Il collabore avec le même réalisateur depuis 1974.',
 'Il a dirigé le Boston Pops Orchestra pendant quatorze ans.',
 'L’un de ses thèmes les plus célèbres tient sur deux notes alternées.'],
 'Spielberg a d’abord cru à une plaisanterie quand le compositeur lui a joué les deux notes du thème des Dents de la mer sur un piano.',
 ['Hans Zimmer','Star Wars']]
];
