/* [kind, titres, année, genres, personnes, studio, len, indices[5], anecdote, voisins?] */
export const GAMES = [
['game','The Legend of Zelda: Ocarina of Time|Ocarina of Time|Zelda Ocarina of Time',1998,'Action-aventure','Shigeru Miyamoto|Eiji Aonuma|Koji Kondo','Nintendo',0,[
 'Jeu vidéo d’action-aventure sorti en 1998 sur une console 64 bits.',
 'Un royaume médiéval-fantastique, un enfant élevé par les esprits d’une forêt.',
 'Développé et édité par le constructeur japonais de Kyoto.',
 'Premier épisode en trois dimensions d’une série née en 1986.',
 'Un instrument à vent sert de télécommande sur le monde : chaque mélodie déclenche un effet.'],
 'Le jeu a introduit le verrouillage de cible, devenu depuis un standard de tout le jeu d’action en 3D.',
 ['Majora’s Mask','A Link to the Past','Breath of the Wild']],
['game','Super Mario Bros.|Super Mario Bros',1985,'Plateforme','Shigeru Miyamoto|Koji Kondo','Nintendo',0,[
 'Jeu de plateforme de 1985, souvent crédité d’avoir relancé toute une industrie.',
 'Des tuyaux verts, des champignons, une princesse toujours dans un autre château.',
 'Vendu avec la console 8 bits du constructeur japonais.',
 'Le héros porte une casquette et une salopette parce que les pixels manquaient pour animer des cheveux.',
 'Le premier monde s’appelle 1-1 et sert encore d’exemple de conception de niveau dans les écoles.'],
 'La moustache et la salopette existent pour des raisons techniques : elles rendaient le visage et les bras lisibles en seize pixels de large.',
 ['Super Mario World','Super Mario 64']],
['game','Minecraft',2011,'Bac à sable|Survie','Markus Persson|Jens Bergensten','Mojang',0,[
 'Jeu vidéo de 2011, esthétique volontairement cubique et basse définition.',
 'Un monde généré à l’infini où l’on creuse le jour et où l’on se cache la nuit.',
 'Développé en Suède par un studio minuscule, racheté deux milliards et demi par Microsoft.',
 'Son créateur signait sous le pseudonyme Notch.',
 'Un monstre vert qui siffle avant d’exploser est né d’une erreur de programmation sur un cochon.'],
 'Le creeper vient d’un bug : en modélisant un cochon, le créateur a inversé longueur et hauteur et a gardé le résultat.',
 []],
['game','Tetris',1984,'Puzzle','Alexeï Pajitnov','Académie des sciences d’URSS',0,[
 'Puzzle vidéo conçu en 1984, l’un des jeux les plus vendus de l’histoire.',
 'Sept formes tombent, on complète des lignes, la musique accélère.',
 'Né dans un institut de recherche soviétique, sur un ordinateur Electronika 60.',
 'Sa bataille de droits entre l’URSS, Nintendo et plusieurs éditeurs a duré des années.',
 'La mélodie associée au jeu est un air traditionnel russe intitulé Korobeïniki.'],
 'Son créateur n’a touché aucune royaltie pendant dix ans : l’État soviétique détenait les droits de tout ce qu’il produisait.',
 []],
['game','Half-Life 2',2004,'Tir à la première personne','Gabe Newell|Marc Laidlaw','Valve',0,[
 'Jeu de tir à la première personne de 2004, sur PC.',
 'Une ville d’Europe de l’Est occupée par une puissance extraterrestre bureaucratique.',
 'Le studio a lancé avec lui une plateforme de distribution qui domine encore le PC.',
 'Le héros, physicien, ne prononce jamais un mot du début à la fin.',
 'Un pistolet gravitationnel permet d’attraper et de projeter tout objet du décor.'],
 'Le code source a fuité un an avant la sortie, retardant le jeu. Le pirate allemand a fini par correspondre avec le patron du studio.',
 ['Half-Life','Portal']],
['game','Portal',2007,'Puzzle|Tir à la première personne','Kim Swift|Erik Wolpaw|Ellen McLain','Valve',0,[
 'Jeu de réflexion à la première personne sorti en 2007, très court.',
 'Un complexe de test aseptisé, sans autre humain que la cobaye.',
 'Développé par le même studio que Half-Life, à partir d’un projet étudiant nommé Narbacular Drop.',
 'Une intelligence artificielle sarcastique commente chaque échec de la joueuse.',
 'Deux portails posés sur des surfaces différentes conservent l’élan : on tombe pour aller plus haut.'],
 'La chanson du générique de fin, écrite par Jonathan Coulton, a lancé la mode des chansons de fin dans le jeu vidéo.',
 ['Portal 2','Half-Life 2']],
['game','The Elder Scrolls V: Skyrim|Skyrim',2011,'Jeu de rôle','Todd Howard|Jeremy Soule','Bethesda',0,[
 'Jeu de rôle en monde ouvert de 2011, réédité sur à peu près tout ce qui a un écran.',
 'Une province nordique enneigée, une guerre civile, et des dragons qui reviennent.',
 'Cinquième épisode d’une série américaine commencée en 1994.',
 'Le héros est un enfant de dragon capable de crier dans une langue draconique.',
 'Une plaisanterie sur une flèche reçue au genou est devenue l’un des mèmes les plus repris du jeu vidéo.'],
 'Le studio a enregistré plus de soixante mille lignes de dialogue, dont beaucoup partagées par des dizaines de villageois interchangeables.',
 ['Oblivion','Fallout 3']],
['game','The Witcher 3: Wild Hunt|The Witcher 3',2015,'Jeu de rôle','Marcin Iwiński|Marcin Przybyłowicz','CD Projekt Red',0,[
 'Jeu de rôle en monde ouvert de 2015, développé en Pologne.',
 'Un continent ravagé par la guerre, où l’on est payé pour tuer des monstres.',
 'Adapté d’une série de romans d’Andrzej Sapkowski, bien avant la série télé.',
 'Le héros aux cheveux blancs boit des potions et se bat avec deux épées.',
 'Un jeu de cartes intégré, le Gwent, a fini par exister en jeu séparé.'],
 'L’auteur des romans avait vendu ses droits pour une somme forfaitaire, refusant un pourcentage. Il a ensuite réclamé une renégociation.',
 ['Cyberpunk 2077','The Witcher 2']],
['game','Dark Souls',2011,'Action-RPG','Hidetaka Miyazaki|Motoi Sakuraba','FromSoftware',0,[
 'Action-RPG japonais de 2011, réputé pour sa difficulté.',
 'Un royaume en fin de cycle, où le feu s’éteint et où les morts ne meurent plus vraiment.',
 'Développé par un studio de Tokyo, sous la direction d’un ancien employé d’Oracle.',
 'Aucune carte, aucun journal de quête : l’histoire se lit dans la description des objets.',
 'Les feux de camp servent de points de sauvegarde et ressuscitent tous les ennemis.'],
 'Son réalisateur a découvert la fantasy par des livres en anglais qu’il ne comprenait qu’à moitié : il comblait les trous en imaginant. C’est devenu sa méthode de narration.',
 ['Demon’s Souls','Bloodborne','Elden Ring']],
['game','Bloodborne',2015,'Action-RPG','Hidetaka Miyazaki|Ryan Amon','FromSoftware',0,[
 'Action-RPG de 2015, exclusif à une console de salon.',
 'Une cité victorienne rongée par une maladie du sang et une nuit de chasse interminable.',
 'Même studio japonais que Dark Souls, en coproduction avec Sony.',
 'Le récit bascule progressivement de l’horreur gothique vers le cosmique lovecraftien.',
 'On soigne ses blessures en frappant l’ennemi juste après avoir été touché.'],
 'Le mot « sang » ou ses dérivés apparaissent dans plus de la moitié des noms d’objets du jeu.',
 ['Dark Souls','Sekiro']],
['game','Elden Ring',2022,'Action-RPG','Hidetaka Miyazaki|George R. R. Martin','FromSoftware',0,[
 'Action-RPG en monde ouvert sorti en 2022, immense succès critique et commercial.',
 'Un entre-terre morcelé où des demi-dieux se disputent les éclats d’un anneau brisé.',
 'Le studio japonais s’est associé à un romancier américain de fantasy pour la mythologie.',
 'Une monture spectrale permet de sauter en double vers les hauteurs.',
 'On invoque d’autres joueurs en posant un signe doré au sol, sans jamais leur parler.'],
 'L’écrivain invité n’a pas écrit le scénario du jeu : il a rédigé la mythologie ancienne, des siècles avant le début de l’aventure.',
 ['Dark Souls','Bloodborne']],
['game','Red Dead Redemption 2',2018,'Action-aventure|Western','Dan Houser|Woody Jackson','Rockstar Games',0,[
 'Action-aventure en monde ouvert de 2018, western crépusculaire.',
 'Une bande de hors-la-loi en fuite alors que l’Ouest américain se referme, en 1899.',
 'Développé par le studio de Grand Theft Auto, après huit ans de production.',
 'La barbe du personnage pousse en temps réel et doit être taillée.',
 'Les chevaux ont un système d’attachement affectif, et leur crottin est simulé.'],
 'Le jeu contient environ 500 000 lignes de dialogue et plus de 1 200 acteurs et figurants ont participé à la capture de mouvement.',
 ['Grand Theft Auto V','Red Dead Redemption']],
['game','Grand Theft Auto V|GTA V|GTA 5',2013,'Action-aventure','Dan Houser|Sam Houser','Rockstar Games',0,[
 'Action-aventure en monde ouvert de 2013, l’un des produits de divertissement les plus rentables jamais créés.',
 'Une Californie du Sud satirique : plages, collines, banques à braquer.',
 'Développé par un studio britannique installé à Édimbourg.',
 'Trois protagonistes jouables que l’on permute d’une pression de touche.',
 'Son mode en ligne rapporte encore de l’argent plus de dix ans après la sortie.'],
 'Le jeu a rapporté 800 millions de dollars en vingt-quatre heures, un record que peu de films ou d’albums ont approché.',
 ['Red Dead Redemption 2','GTA San Andreas']],
['game','The Last of Us',2013,'Action-aventure|Survie','Neil Druckmann|Gustavo Santaolalla','Naughty Dog',0,[
 'Action-aventure de 2013, adapté en série télévisée dix ans plus tard.',
 'Une Amérique effondrée par un champignon parasite qui prend le contrôle des corps.',
 'Développé par le studio californien d’Uncharted.',
 'Musique à la guitare composée par un Argentin déjà oscarisé pour le cinéma.',
 'Un contrebandier vieillissant doit convoyer une adolescente immunisée à travers le pays.'],
 'Le champignon du jeu existe vraiment : le cordyceps infecte les fourmis et dirige leur comportement. Il ne peut pas survivre à la température humaine.',
 ['Uncharted 2','The Last of Us Part II']],
['game','Uncharted 2: Among Thieves|Uncharted 2',2009,'Action-aventure','Amy Hennig|Nolan North','Naughty Dog',0,[
 'Action-aventure de 2009, cinématographique jusque dans le montage.',
 'Un chasseur de trésors bavard sur la piste de Shambhala, du Népal au Tibet.',
 'Développé par le studio américain qui fera ensuite The Last of Us.',
 'Une séquence entière se déroule dans un train qui déraille, jouée à l’envers du récit.',
 'Le héros escalade tout ce qui dépasse et s’en excuse par une vanne.'],
 'La séquence du train a été construite comme un décor réel monté sur vérins, filmé avant d’être recréé en jeu.',
 ['Uncharted 4','The Last of Us']],
['game','God of War',2018,'Action-aventure','Cory Barlog|Bear McCreary','Santa Monica Studio',0,[
 'Action-aventure de 2018, redémarrage d’une série née en 2005.',
 'La mythologie nordique remplace le panthéon grec des épisodes précédents.',
 'Développé par un studio interne de Sony, à Los Angeles.',
 'Le jeu entier est filmé en un seul plan-séquence apparent, sans aucune coupe.',
 'Un père taciturne apprend à parler à son fils en traversant neuf royaumes.'],
 'Le mot « boy » prononcé par le père est devenu si célèbre que le studio a compté ses occurrences : plus de cent.',
 ['God of War Ragnarök']],
['game','Shadow of the Colossus',2005,'Action-aventure','Fumito Ueda|Kow Otani','Team Ico',0,[
 'Action-aventure japonais de 2005, presque entièrement vide.',
 'Une terre interdite sans ennemis ordinaires : seulement seize géants à abattre.',
 'Développé par la même équipe que Ico, chez l’éditeur japonais Sony.',
 'Pas de villages, pas de marchands, pas de dialogues : un cheval et un arc.',
 'Chaque géant est un niveau à escalader, en cherchant le point faible sur son corps.'],
 'Le concepteur a retiré du jeu tout ce qui n’était pas indispensable — une méthode qu’il appelle « design par soustraction ».',
 ['Ico','The Last Guardian']],
['game','Journey',2012,'Aventure','Jenova Chen|Austin Wintory','thatgamecompany',0,[
 'Jeu d’aventure de 2012, terminé en environ deux heures.',
 'Un désert doré et une montagne lointaine vers laquelle on avance sans explication.',
 'Développé par un petit studio américain, publié par Sony.',
 'Première bande originale de jeu vidéo nommée aux Grammy Awards.',
 'On croise parfois un autre joueur, sans pouvoir lui parler ni connaître son nom.'],
 'Les compagnons de route sont de vrais joueurs, dont le pseudonyme n’est révélé qu’au générique de fin — souvent après avoir voyagé des heures ensemble.',
 []],
['game','Celeste',2018,'Plateforme','Maddy Thorson|Lena Raine','Extremely OK Games',0,[
 'Jeu de plateforme exigeant sorti en 2018, en pixel art.',
 'L’ascension d’une montagne canadienne qui matérialise l’anxiété de celle qui la gravit.',
 'Né d’un prototype créé en quatre jours lors d’une game jam.',
 'Musique au piano de Lena Raine, souvent citée parmi les meilleures du médium.',
 'Un compteur affiche sans jugement le nombre de morts, qui se compte en milliers.'],
 'Le jeu inclut un mode d’assistance permettant de ralentir le temps ou de devenir invincible, présenté sans culpabilisation aucune.',
 []],
['game','Hollow Knight',2017,'Metroidvania','Ari Gibson|Christopher Larkin','Team Cherry',0,[
 'Metroidvania de 2017, dessiné à la main, développé par trois personnes en Australie.',
 'Un royaume souterrain d’insectes, ravagé par une infection lumineuse.',
 'Financé par une campagne participative qui avait à peine atteint son objectif.',
 'Le personnage principal ne parle pas et porte un masque en forme de coquille.',
 'On se soigne en canalisant une énergie blanche, immobile et vulnérable.'],
 'Les trois développeurs avaient promis quelques extensions gratuites : elles ont fini par doubler la taille du jeu.',
 ['Silksong','Ori and the Blind Forest']],
['game','Undertale',2015,'Jeu de rôle','Toby Fox','Toby Fox',0,[
 'Jeu de rôle de 2015, réalisé presque entièrement par une seule personne.',
 'Un monde souterrain de monstres, où l’on peut choisir de n’en tuer aucun.',
 'Financé sur Kickstarter pour environ cinquante mille dollars.',
 'Les combats mêlent tour par tour et esquive façon shoot’em up.',
 'Le jeu se souvient de vos parties précédentes, même après effacement de la sauvegarde.'],
 'Son auteur a composé la totalité de la bande-son et refuse toujours de vendre les droits d’adaptation.',
 ['Deltarune']],
['game','Hades',2020,'Roguelite|Action','Greg Kasavin|Darren Korb','Supergiant Games',0,[
 'Jeu d’action à structure roguelite sorti en 2020.',
 'Le fils du dieu des morts tente de fuir les Enfers, encore et encore.',
 'Développé par un studio américain déjà connu pour Bastion et Transistor.',
 'Premier jeu vidéo à remporter un prix Hugo.',
 'Chaque mort relance la partie, et les personnages commentent votre échec avec de nouveaux dialogues.'],
 'Le jeu contient plus de trois cent mille mots de dialogue, soit davantage que la plupart des romans-fleuves.',
 ['Bastion','Transistor']],
['game','Stardew Valley',2016,'Simulation','Eric Barone','ConcernedApe',0,[
 'Simulation de vie rurale sortie en 2016, en pixel art.',
 'On hérite d’une ferme à l’abandon et on quitte un travail de bureau déprimant.',
 'Conçu, dessiné, programmé et composé par une seule personne, pendant quatre ans.',
 'Hommage assumé à une série japonaise de fermes des années 1990.',
 'Un centre communautaire délabré se répare en offrant des paniers de récoltes à des esprits.'],
 'Son créateur a refait entièrement les graphismes plusieurs fois, uniquement pour progresser en dessin pendant le développement.',
 ['Harvest Moon','Animal Crossing']],
['game','Among Us',2018,'Party game','Innersloth','Innersloth',0,[
 'Jeu multijoueur de 2018, devenu phénomène mondial deux ans après sa sortie.',
 'Un vaisseau spatial, des tâches à accomplir, et un imposteur parmi l’équipage.',
 'Développé par un studio américain de trois personnes.',
 'Le jeu était quasiment mort avant d’exploser grâce aux diffusions en direct.',
 'Les personnages sont des capsules colorées, et l’on vote pour éjecter un suspect.'],
 'Le studio avait annoncé une suite, puis l’a annulée pour concentrer ses efforts sur le jeu original enfin populaire.',
 []],
['game','Fortnite',2017,'Battle royale','Tim Sweeney|Donald Mustard','Epic Games',0,[
 'Jeu multijoueur gratuit de 2017, financé par des objets cosmétiques.',
 'Cent joueurs sur une île qui rétrécit, avec la possibilité de bâtir des murs en pleine fusillade.',
 'Développé par le studio américain à l’origine du moteur Unreal.',
 'Des concerts virtuels y ont réuni des dizaines de millions de spectateurs simultanés.',
 'La construction instantanée distingue ce battle royale de tous ses concurrents.'],
 'Le mode qui a fait sa fortune a été ajouté en deux mois par une petite équipe, alors que le jeu principal était un tout autre projet.',
 ['PUBG','Apex Legends']],
['game','Counter-Strike',2000,'Tir tactique','Minh Le|Jess Cliffe','Valve',0,[
 'Jeu de tir compétitif en équipe, publié en version définitive en 2000.',
 'Terroristes contre antiterroristes, une bombe à poser, aucune résurrection avant la fin de la manche.',
 'Né comme modification amateur d’un autre jeu du même éditeur.',
 'Ses cartes de Dust portent des noms devenus universels chez les joueurs.',
 'On achète son équipement en début de manche avec l’argent gagné à la précédente.'],
 'Le jeu était à l’origine un mod gratuit créé par deux étudiants ; l’éditeur les a embauchés et a racheté le projet.',
 ['Half-Life 2','Valorant']],
['game','Doom',1993,'Tir à la première personne','John Carmack|John Romero|Bobby Prince','id Software',0,[
 'Jeu de tir à la première personne de 1993, distribué en partie gratuitement.',
 'Une base martienne dont les portails ont ouvert sur quelque chose de nettement plus chaud.',
 'Développé au Texas par une poignée de programmeurs et un moteur révolutionnaire.',
 'Le jeu a été porté depuis sur calculatrices, imprimantes et tests de grossesse.',
 'Une tronçonneuse figure au premier rang de l’arsenal.'],
 'Le code source a été publié en 1997, ce qui explique qu’on puisse y jouer aujourd’hui sur à peu près n’importe quel appareil doté d’un écran.',
 ['Quake','Wolfenstein 3D']],
['game','Metal Gear Solid',1998,'Infiltration','Hideo Kojima|Yoji Shinkawa','Konami',0,[
 'Jeu d’infiltration japonais de 1998, sur console 32 bits.',
 'Une base nucléaire enfouie en Alaska, prise par une unité d’élite renégate.',
 'Conçu par un auteur japonais obsédé de cinéma américain des années 1980.',
 'Un combat exige de brancher la manette sur le second port du système.',
 'Un ennemi psychique prétend lire dans la mémoire de votre carte de sauvegarde.'],
 'Psycho Mantis lit réellement la carte mémoire et commente les autres jeux de l’éditeur que vous possédez.',
 ['Metal Gear Solid 3','Death Stranding']],
['game','Final Fantasy VII|Final Fantasy 7',1997,'Jeu de rôle','Hironobu Sakaguchi|Nobuo Uematsu|Tetsuya Nomura','Square',0,[
 'Jeu de rôle japonais de 1997, premier de sa série en trois dimensions.',
 'Une mégapole alimentée par l’aspiration de l’énergie vitale de la planète.',
 'Passage de la cartouche au CD, ce qui a fait basculer l’éditeur d’une console à l’autre.',
 'Musique de Nobuo Uematsu, dont un thème d’orgue est devenu un standard de concert.',
 'La mort d’un personnage jouable au milieu du récit a traumatisé toute une génération.'],
 'Le jeu a été le premier de la série publié en français, ce qui a ouvert le genre du RPG japonais à toute une partie de l’Europe.',
 ['Final Fantasy X','Chrono Trigger']],
['game','Chrono Trigger',1995,'Jeu de rôle','Hironobu Sakaguchi|Yuji Horii|Akira Toriyama|Yasunori Mitsuda','Square',0,[
 'Jeu de rôle japonais de 1995, sur console 16 bits.',
 'Une fête foraine, une machine à voyager dans le temps, et une planète à sauver de son futur.',
 'Réunion exceptionnelle des créateurs de Final Fantasy et de Dragon Quest.',
 'Personnages dessinés par l’auteur de Dragon Ball.',
 'Le jeu propose plus d’une douzaine de fins selon le moment où l’on affronte le boss final.'],
 'L’équipe réunie pour ce jeu a été surnommée la « Dream Team » par la presse japonaise, un terme jamais réutilisé depuis avec autant de sérieux.',
 ['Final Fantasy VII','Dragon Quest']],
['game','Pokémon Rouge et Bleu|Pokemon Rouge|Pokemon Bleu|Pokémon Rouge',1996,'Jeu de rôle','Satoshi Tajiri|Ken Sugimori|Junichi Masuda','Nintendo',0,[
 'Jeu de rôle japonais de 1996, sorti sur une console portable monochrome.',
 'Une région où l’on capture des créatures pour les faire combattre entre elles.',
 'Développé par un studio au bord de la faillite pendant six ans de production.',
 'Deux versions vendues séparément obligeaient à échanger avec un ami par câble.',
 'Un bug célèbre permet de rencontrer une créature difforme au bord d’une plage.'],
 'Le créateur collectionnait les insectes enfant ; l’échange par câble reproduit littéralement le troc entre gamins de son quartier.',
 ['Pokémon Or et Argent']],
['game','Street Fighter II',1991,'Combat','Akira Nishitani|Yoko Shimomura','Capcom',0,[
 'Jeu de combat en un contre un sorti en 1991, d’abord en salle d’arcade.',
 'Huit personnages nationaux affrontent quatre boss à travers le monde.',
 'Développé par un éditeur japonais d’Osaka.',
 'Il a inventé la grammaire du genre : quarts de cercle, coups spéciaux, annulations.',
 'Un yogi indien crache du feu, un militaire brésilien tourne sur lui-même.'],
 'Les enchaînements, pilier de tout jeu de combat depuis, sont nés d’un bug que les développeurs ont décidé de conserver.',
 ['Tekken','Mortal Kombat']],
['game','Sonic the Hedgehog|Sonic',1991,'Plateforme','Yuji Naka|Naoto Ohshima|Masato Nakamura','Sega',0,[
 'Jeu de plateforme de 1991, conçu comme arme commerciale contre un plombier moustachu.',
 'Des boucles, des ressorts, des anneaux dorés à ramasser en courant.',
 'Développé par le concurrent japonais direct de Nintendo à l’époque.',
 'Musique composée par le bassiste d’un groupe de pop japonais à succès.',
 'Le héros est bleu parce que c’était la couleur du logo de l’éditeur.'],
 'Le personnage devait initialement être un lapin capable d’attraper des objets avec ses oreilles ; l’idée a été abandonnée pour privilégier la vitesse.',
 ['Super Mario Bros.']],
['game','Silent Hill 2',2001,'Survival horror','Masahiro Ito|Akira Yamaoka','Konami',0,[
 'Jeu d’horreur japonais de 2001, souvent cité comme le sommet narratif du genre.',
 'Une ville de bord de lac noyée dans le brouillard, où chacun voit ses propres monstres.',
 'Le brouillard servait aussi à masquer les limites techniques de la console.',
 'Musique industrielle et mélancolique d’Akira Yamaoka.',
 'Une créature à tête pyramidale n’existe que dans l’esprit du protagoniste, qui se punit lui-même.'],
 'Le monstre le plus célèbre du jeu n’apparaît que quelques minutes, mais il est devenu l’image de toute la série.',
 ['Resident Evil 4','Silent Hill']],
['game','Resident Evil 4',2005,'Survival horror|Action','Shinji Mikami|Misao Senbongi','Capcom',0,[
 'Jeu d’action-horreur de 2005, qui a réinventé la caméra à l’épaule.',
 'Un village espagnol reculé où les habitants sont contrôlés par un parasite.',
 'Réalisé par le créateur de la série, après plusieurs versions abandonnées.',
 'Un marchand mystérieux vend des armes au milieu de nulle part.',
 'La mission consiste à récupérer la fille du président des États-Unis.'],
 'Une version antérieure du jeu, trop fantomatique, a été détachée du projet et transformée en Devil May Cry.',
 ['Silent Hill 2','Resident Evil 2']],
['game','BioShock',2007,'Tir à la première personne','Ken Levine|Garry Schyman','2K Games',0,[
 'Jeu de tir à la première personne de 2007, à forte charge politique.',
 'Une cité sous-marine bâtie par un industriel pour échapper à toute règle collective.',
 'Développé par le studio héritier de System Shock.',
 'Le décor est un art déco des années 1950 rongé par les fuites d’eau.',
 'Une phrase de politesse répétée par un allié dissimule un conditionnement mental.'],
 'La ville de Rapture est une réponse critique aux romans d’Ayn Rand ; le nom de son fondateur, Andrew Ryan, en est l’anagramme approximative.',
 ['System Shock 2','BioShock Infinite']],
['game','Mass Effect 2',2010,'Jeu de rôle|Action','Casey Hudson|Jack Wall','BioWare',0,[
 'Jeu de rôle d’action de 2010, deuxième volet d’une trilogie spatiale.',
 'Une galaxie menacée par une intelligence machinique cyclique, et un équipage à recruter.',
 'Développé par un studio canadien racheté par Electronic Arts.',
 'Les sauvegardes du premier épisode se transfèrent et modifient le récit.',
 'La mission finale peut tuer n’importe quel membre de l’équipage selon vos choix.'],
 'La mission suicide finale calcule la survie de chaque personnage d’après des décisions prises parfois vingt heures plus tôt.',
 ['Mass Effect 3','Dragon Age']],
['game','Death Stranding',2019,'Action|Livraison','Hideo Kojima|Ludvig Forssell','Kojima Productions',0,[
 'Jeu d’action de 2019, premier titre de son auteur après sa rupture avec son ancien éditeur.',
 'Une Amérique éclatée où les vivants et les morts se sont mélangés sous une pluie qui vieillit.',
 'Le héros est incarné par Norman Reedus, avec Léa Seydoux et Mads Mikkelsen au générique.',
 'Le cœur du jeu consiste à porter des colis en gardant l’équilibre.',
 'Les structures bâties par d’autres joueurs apparaissent dans votre monde sans qu’on se rencontre jamais.'],
 'Guillermo del Toro et Nicolas Winding Refn prêtent leur visage à des personnages, mais pas leur voix.',
 ['Metal Gear Solid']],
['game','Cyberpunk 2077',2020,'Jeu de rôle|Action','CD Projekt Red|Marcin Przybyłowicz|Keanu Reeves','CD Projekt Red',0,[
 'Jeu de rôle en monde ouvert sorti fin 2020, dans un état catastrophique sur consoles anciennes.',
 'Une mégapole californienne dystopique où l’on se greffe des implants pour rester compétitif.',
 'Développé par le studio polonais de The Witcher, d’après un jeu de rôle papier de 1988.',
 'Keanu Reeves double un rockeur terroriste installé dans votre tête.',
 'Le jeu a été retiré du magasin d’une console pendant plusieurs mois après sa sortie.'],
 'Retiré de la boutique PlayStation en 2020, il y est revenu en 2021 et a été réhabilité par une extension et une série animée.',
 ['The Witcher 3']],
['game','Disco Elysium',2019,'Jeu de rôle','Robert Kurvitz|British Sea Power','ZA/UM',0,[
 'Jeu de rôle de 2019 sans le moindre combat, écrit par un romancier estonien.',
 'Une ville portuaire en ruine après une révolution ratée, et un cadavre pendu à un arbre.',
 'Développé par un studio estonien à partir d’un univers de jeu de rôle sur table.',
 'Vos vingt-quatre compétences sont des voix intérieures qui débattent entre elles.',
 'Le protagoniste est un inspecteur amnésique et alcoolique qui ignore jusqu’à son nom.'],
 'On peut mourir dès la première scène en tentant de décrocher sa cravate d’un ventilateur de plafond.',
 ['Planescape Torment']],
['game','Papers, Please',2013,'Puzzle|Simulation','Lucas Pope','3909 LLC',0,[
 'Jeu de 2013 dans lequel on travaille au guichet d’un poste-frontière.',
 'Un pays fictif d’Europe de l’Est, l’Arstotzka, en 1982.',
 'Créé par un ancien de Naughty Dog, seul, en neuf mois.',
 'Le salaire de fin de journée sert à chauffer l’appartement ou à soigner un enfant malade.',
 'Chaque règle ajoutée transforme la bureaucratie en dilemme moral.'],
 'Son auteur a ensuite réalisé Return of the Obra Dinn, également seul, dans un noir et blanc tramé à un bit.',
 ['Return of the Obra Dinn']],
['game','The Legend of Zelda: Breath of the Wild|Breath of the Wild',2017,'Action-aventure','Eiji Aonuma|Hidemaro Fujibayashi','Nintendo',0,[
 'Action-aventure de 2017, sorti au lancement d’une console hybride.',
 'Un royaume dévasté cent ans après la catastrophe, entièrement ouvert dès la première heure.',
 'Le prototype a été présenté en interne sous forme de jeu en deux dimensions façon 1986.',
 'On grimpe absolument n’importe quelle paroi, tant que l’endurance suit.',
 'Les armes se brisent, ce qui oblige à changer constamment de manière de se battre.'],
 'Les développeurs ont conçu la carte à partir de la topographie réelle de Kyoto, pour calibrer les distances de marche.',
 ['Ocarina of Time','Tears of the Kingdom']]
];
