export const SCREEN = [
['movie','Les Dents de la mer|Jaws',1975,'Aventure|Thriller|Horreur','Steven Spielberg|Roy Scheider|John Williams','Universal',124,[
 'Film américain de 1975, souvent considéré comme le premier blockbuster estival.',
 'Une station balnéaire refuse de fermer ses plages en pleine saison.',
 'Réalisé par un cinéaste de vingt-sept ans, sur un tournage catastrophique.',
 'Deux notes suffisent à annoncer la menace.',
 'La créature n’apparaît presque pas pendant la première heure.'],
 'Le requin mécanique tombait sans arrêt en panne. C’est cette avarie qui a forcé Spielberg à le cacher — et qui a fait la peur du film.'],
['movie','Star Wars, épisode IV : Un nouvel espoir|Star Wars|La Guerre des étoiles',1977,'Science-Fiction|Aventure','George Lucas|Mark Hamill|John Williams','Lucasfilm',121,[
 'Space opera américain de 1977, tourné en Tunisie et en Angleterre.',
 'Une princesse capturée, un fermier orphelin, un empire galactique.',
 'Le studio n’y croyait pas et a cédé au réalisateur les droits dérivés.',
 'Musique symphonique à contre-courant de la mode électronique de l’époque.',
 'Le récit reprend la trame d’un film de samouraïs de Kurosawa.'],
 'Lucas a échangé une part de salaire contre les droits de merchandising. Le studio a accepté en riant : ce choix l’a rendu milliardaire.'],
['movie','E.T. l’extra-terrestre|E.T.',1982,'Science-Fiction|Familial|Aventure','Steven Spielberg|John Williams|Henry Thomas',' Universal',115,[
 'Film américain de 1982, tourné en grande partie à hauteur d’enfant.',
 'Une banlieue pavillonnaire californienne et un visiteur oublié par les siens.',
 'La caméra reste à un mètre du sol pendant presque tout le film.',
 'Le tournage s’est déroulé dans l’ordre chronologique pour aider les enfants acteurs.',
 'Une silhouette de vélo passe devant la lune.'],
 'Les bonbons du film ont vu leurs ventes tripler. La marque concurrente, initialement pressentie, avait refusé de participer.'],
['movie','Princesse Mononoké|Mononoke Hime',1997,'Animation|Aventure|Fantastique','Hayao Miyazaki|Joe Hisaishi','Studio Ghibli',134,[
 'Animation japonaise de 1997, nettement plus violente que le reste de son studio.',
 'Une forêt ancestrale contre une cité sidérurgique, sans camp clairement fautif.',
 'Le réalisateur a supervisé lui-même plus de quatre-vingt mille dessins.',
 'Le film met en scène des divinités animales et une jeune fille élevée par des loups.',
 'Le héros est frappé d’une malédiction au bras dès la première scène.'],
 'C’est le dernier grand film du studio réalisé quasi intégralement à la main. Le réalisateur a corrigé personnellement des dizaines de milliers d’images.'],
['movie','Akira',1988,'Animation|Science-Fiction|Action','Katsuhiro Otomo|Shoji Yamashiro','Toho',124,[
 'Animation japonaise de 1988, qui a fait connaître le genre en Occident.',
 'Un Néo-Tokyo reconstruit après une explosion, gangs de motards et essais militaires.',
 'Adapté par l’auteur lui-même de son propre manga, alors inachevé.',
 'Les bouches des personnages ont été animées d’après un enregistrement préalable, cas rarissime au Japon.',
 'Une moto rouge qui dérape sur des kilomètres est devenue une image citée partout.'],
 'Le film a coûté près de dix fois le budget d’un anime standard de l’époque, financé par un consortium d’éditeurs et de fabricants de disques.'],
['movie','Ghost in the Shell',1995,'Animation|Science-Fiction','Mamoru Oshii|Kenji Kawai','Production I.G',83,[
 'Animation japonaise de 1995, contemplative malgré son sujet policier.',
 'Un futur où le cerveau se connecte au réseau et où l’identité devient piratable.',
 'Le film a directement influencé les frères et sœurs Wachowski.',
 'Musique de chœurs traditionnels japonais sur images cyberpunk.',
 'L’héroïne est un cyborg qui doute d’avoir jamais eu un corps.'],
 'La séquence de pluie et de vitrines, sans dialogue ni action, dure trois minutes : le producteur voulait la couper, le réalisateur a menacé de partir.'],
['movie','Your Name|Kimi no Na wa',2016,'Animation|Romance|Fantastique','Makoto Shinkai|Radwimps','CoMix Wave',106,[
 'Animation japonaise de 2016, immense succès au Japon.',
 'Une lycéenne de campagne et un lycéen de Tokyo échangent de corps par intermittence.',
 'Son réalisateur a longtemps travaillé seul sur ses courts métrages.',
 'La bande originale est signée par un groupe de rock japonais.',
 'Une comète traverse le ciel et sépare les deux récits par plus qu’une distance.'],
 'Le film a dépassé Le Voyage de Chihiro au box-office japonais, ce que personne n’avait réussi depuis quinze ans.'],
['movie','Spider-Man: New Generation|Into the Spider-Verse',2018,'Animation|Action|Aventure','Peter Ramsey|Bob Persichetti|Rodney Rothman','Sony Pictures Animation',117,[
 'Animation américaine de 2018, Oscar du meilleur film d’animation.',
 'Plusieurs versions du même héros venues d’univers parallèles se rencontrent.',
 'Le style imite la trame d’impression des comics, jusqu’aux erreurs de repérage des couleurs.',
 'Les animateurs ont travaillé en douze images par seconde pour le héros débutant, puis vingt-quatre.',
 'Le protagoniste est un adolescent de Brooklyn nommé Miles.'],
 'L’équipe a inventé plus d’une centaine d’outils spécifiques : le studio a déposé des brevets sur des techniques d’animation créées pour ce seul film.'],
['movie','Le Grand Bleu',1988,'Aventure|Drame','Luc Besson|Jean Reno|Éric Serra','Gaumont',132,[
 'Film français de 1988, échec critique et triomphe public en France.',
 'Deux amis d’enfance s’affrontent en apnée profonde, en Méditerranée.',
 'Inspiré de la rivalité réelle entre Jacques Mayol et Enzo Maiorca.',
 'La version américaine a reçu une autre fin et une autre musique.',
 'Les dauphins tiennent lieu de famille au personnage principal.'],
 'Le film est resté un an à l’affiche en France, avec plus de neuf millions d’entrées, alors que la critique l’avait éreinté à sa sortie.'],
['movie','Les Tontons flingueurs',1963,'Comédie|Crime','Georges Lautner|Michel Audiard|Lino Ventura','Gaumont',105,[
 'Comédie policière française de 1963, en noir et blanc.',
 'Un industriel doit gérer l’héritage criminel d’un ami mourant.',
 'Les dialogues sont signés par le plus cité des dialoguistes français.',
 'Le film a été un succès modeste avant de devenir culte par la télévision.',
 'Une scène de cuisine nocturne autour d’un alcool artisanal est récitée par cœur en France.'],
 'La scène de la cuisine a été tournée avec du vrai alcool dans les verres. Les acteurs improvisent visiblement à mesure que la nuit avance.'],
['movie','La Grande Vadrouille',1966,'Comédie|Guerre','Gérard Oury|Bourvil|Louis de Funès','Gaumont',132,[
 'Comédie française de 1966, record d’entrées en France pendant plus de trente ans.',
 'Un chef d’orchestre et un peintre en bâtiment convoient des aviateurs anglais.',
 'Le tandem comique oppose un timide et un colérique.',
 'Une partie du film se déroule dans les hospices de Beaune.',
 'Une scène de bains turcs sert de rendez-vous secret, sur un air d’opérette.'],
 'Ses 17 millions d’entrées n’ont été dépassées qu’en 1998 par Titanic, puis par Bienvenue chez les Ch’tis.'],
['movie','Le Dîner de cons',1998,'Comédie','Francis Veber|Jacques Villeret|Thierry Lhermitte','Gaumont',80,[
 'Comédie française de 1998, adaptée d’une pièce de théâtre du même auteur.',
 'Des bourgeois organisent un dîner pour se moquer d’un invité ridicule.',
 'Presque tout le film se déroule dans un seul appartement.',
 'Le protagoniste construit des monuments en allumettes.',
 'Un contrôleur fiscal invité par erreur retourne la soirée.'],
 'Jacques Villeret avait déjà joué le rôle plus de neuf cents fois au théâtre avant le tournage.'],
['movie','OSS 117 : Le Caire, nid d’espions',2006,'Comédie|Aventure','Michel Hazanavicius|Jean Dujardin','Gaumont',99,[
 'Comédie française de 2006, pastiche du film d’espionnage des années 1950.',
 'Un agent français au Caire, sûr de lui et parfaitement ignorant.',
 'Réalisé par le futur auteur de The Artist.',
 'Le personnage vient d’une série de romans antérieure à James Bond.',
 'Le héros réveille tout un quartier en imitant un appel à la prière.'],
 'Le personnage littéraire est né en 1949, soit quatre ans avant James Bond. La parodie précède donc l’original qu’elle semble viser.'],
['movie','Un prophète',2009,'Crime|Drame','Jacques Audiard|Tahar Rahim|Niels Arestrup','UGC',155,[
 'Film français de 2009, Grand Prix à Cannes.',
 'Un jeune homme illettré entre en prison pour six ans et en ressort tout autre.',
 'Réalisé par le cinéaste de De rouille et d’os et Dheepan.',
 'Le rôle principal a été confié à un acteur alors inconnu.',
 'Un fantôme accompagne le protagoniste dans sa cellule.'],
 'Tahar Rahim a appris le corse et l’arabe pour le rôle, et a été choisi après une audition alors qu’il n’avait jamais tenu de premier rôle.'],
['movie','Les Quatre Cents Coups',1959,'Drame','François Truffaut|Jean-Pierre Léaud','Les Films du Carrosse',99,[
 'Film français de 1959, premier long métrage de son réalisateur.',
 'Un adolescent parisien fugue, ment, vole une machine à écrire.',
 'L’un des actes fondateurs d’un mouvement critique devenu école de cinéma.',
 'Largement autobiographique : le réalisateur avait été placé en centre d’observation.',
 'Le dernier plan s’arrête sur un arrêt sur image, face à la mer.'],
 'L’acteur principal, choisi par petite annonce, a rejoué le même personnage dans quatre autres films, sur vingt ans.'],
['movie','À bout de souffle',1960,'Crime|Drame','Jean-Luc Godard|Jean-Paul Belmondo|Jean Seberg','Les Films Impéria',90,[
 'Film français de 1960, tourné en quatre semaines avec une équipe minuscule.',
 'Un petit voyou en cavale et une Américaine qui vend des journaux sur les Champs-Élysées.',
 'Le scénario tient sur quelques feuillets écrits par un autre cinéaste du même mouvement.',
 'Les faux raccords, d’abord accidentels, sont devenus une signature.',
 'La caméra était poussée dans un fauteuil roulant, faute de travelling.'],
 'Le film a été monté en coupant à l’intérieur des plans pour tenir la durée. Ce bricolage a donné naissance au jump cut moderne.'],
['movie','Apocalypse Now',1979,'Guerre|Drame','Francis Ford Coppola|Martin Sheen|Marlon Brando','United Artists',147,[
 'Film américain de 1979, Palme d’or, tournage devenu légendaire.',
 'Une remontée de fleuve vers un officier devenu dieu dans la jungle.',
 'Librement adapté d’un roman de Joseph Conrad situé au Congo.',
 'Le tournage aux Philippines a duré plus d’un an et failli tuer son acteur principal.',
 'Des hélicoptères attaquent un village sur une musique de Wagner.'],
 'Coppola a hypothéqué ses biens pour finir le film. Il a résumé le tournage ainsi : nous étions dans la jungle, trop nombreux, et nous sommes devenus fous.'],
['movie','Taxi Driver',1976,'Crime|Drame','Martin Scorsese|Robert De Niro|Bernard Herrmann','Columbia',114,[
 'Film américain de 1976, Palme d’or, New York filmé comme un cloaque.',
 'Un vétéran insomniaque conduit un taxi de nuit et se persuade d’une mission.',
 'Musique de Bernard Herrmann, achevée le jour de sa mort.',
 'Une scène devant un miroir est entièrement improvisée par l’acteur.',
 'Jodie Foster, treize ans, y joue une prostituée mineure.'],
 'De Niro a passé son permis de taxi et conduit réellement dans New York pendant plusieurs semaines avant le tournage.'],
['movie','Orange mécanique|A Clockwork Orange',1971,'Crime|Science-Fiction|Drame','Stanley Kubrick|Malcolm McDowell','Warner Bros.',137,[
 'Film britannique de 1971, adapté d’un roman d’Anthony Burgess.',
 'Une bande de jeunes ultraviolents parlant un argot inventé mêlé de russe.',
 'Son réalisateur l’a lui-même retiré des écrans britanniques pendant vingt-sept ans.',
 'Un traitement de conditionnement force le héros à regarder des images en gardant les yeux ouverts.',
 'Une chanson de comédie musicale américaine accompagne une agression.'],
 'Kubrick a fait retirer le film du Royaume-Uni après des menaces contre sa famille. Il n’y est ressorti qu’en 2000, après sa mort.'],
['movie','Vol au-dessus d’un nid de coucou|One Flew Over the Cuckoo’s Nest',1975,'Drame','Miloš Forman|Jack Nicholson|Louise Fletcher','United Artists',133,[
 'Film américain de 1975, cinq Oscars majeurs, ce qui reste très rare.',
 'Un détenu simule la folie pour éviter les travaux forcés et atterrit en hôpital psychiatrique.',
 'Réalisé par un cinéaste tchèque exilé après 1968.',
 'Tourné dans un véritable hôpital de l’Oregon, avec de vrais patients en figuration.',
 'Une partie de baseball est commentée devant un téléviseur éteint.'],
 'L’auteur du roman a refusé de voir le film jusqu’à sa mort : il reprochait qu’on ait changé le narrateur, un patient amérindien, au profit du personnage de Nicholson.'],
['movie','Le Bon, la Brute et le Truand|Il buono, il brutto, il cattivo',1966,'Western|Aventure','Sergio Leone|Ennio Morricone|Clint Eastwood','United Artists',161,[
 'Western italien de 1966, tourné en Espagne avec des acteurs américains.',
 'Trois hommes cherchent un magot enterré en pleine guerre de Sécession.',
 'Le film est le troisième d’une trilogie qui n’en est pas vraiment une.',
 'Sa musique, sifflée et hurlée, est plus connue que le film lui-même.',
 'Le duel final se joue à trois, dans un cimetière circulaire.'],
 'La musique était composée avant le tournage et diffusée sur le plateau. Le duel final a été chorégraphié sur la partition, comme un ballet.'],
['movie','Casablanca',1942,'Drame|Romance|Guerre','Michael Curtiz|Humphrey Bogart|Ingrid Bergman','Warner Bros.',102,[
 'Film américain de 1942, tourné pendant la guerre qu’il raconte.',
 'Un café tenu par un Américain cynique dans le Maroc sous contrôle de Vichy.',
 'Le scénario était réécrit au jour le jour pendant le tournage.',
 'Les acteurs ignoraient jusqu’à la fin qui partirait avec qui.',
 'Une chanson jouée au piano ravive une histoire parisienne.'],
 'Ingrid Bergman a joué toutes ses scènes sans savoir lequel des deux hommes son personnage choisirait : le scénario n’était pas écrit.'],
['movie','Les Temps modernes|Modern Times',1936,'Comédie|Drame','Charlie Chaplin','United Artists',87,[
 'Film américain de 1936, muet alors que le parlant régnait depuis huit ans.',
 'Un ouvrier à la chaîne devient fou à force de serrer des boulons.',
 'Son auteur en est le réalisateur, le scénariste, le compositeur et l’acteur principal.',
 'C’est la dernière apparition d’un personnage vieux de vingt ans.',
 'On y entend la voix du héros pour la première et unique fois, dans une chanson en charabia.'],
 'Chaplin a résisté au parlant pendant presque une décennie : son personnage muet était compris dans le monde entier, la parole l’aurait enfermé dans une langue.'],
['movie','Psychose|Psycho',1960,'Horreur|Thriller|Mystère','Alfred Hitchcock|Anthony Perkins|Bernard Herrmann','Paramount',109,[
 'Film américain de 1960, tourné en noir et blanc pour des raisons de coût et de censure.',
 'Une employée en fuite avec de l’argent s’arrête dans un motel isolé.',
 'Son réalisateur a acheté tous les exemplaires du roman pour préserver la surprise.',
 'L’héroïne apparente meurt au bout de quarante minutes.',
 'Des cordes stridentes accompagnent une scène de douche de quarante-cinq secondes.'],
 'Hitchcock a imposé aux salles d’interdire l’entrée après le début de la séance — une règle inédite qui a fondé notre rapport actuel aux horaires de cinéma.'],
['movie','Sueurs froides|Vertigo',1958,'Mystère|Romance|Thriller','Alfred Hitchcock|James Stewart|Kim Novak','Paramount',128,[
 'Film américain de 1958, tourné à San Francisco.',
 'Un ancien policier acrophobe est engagé pour suivre l’épouse d’un ami.',
 'Il a été un échec relatif avant d’être réévalué comme un sommet.',
 'Un effet optique combinant travelling et zoom inverse a été inventé pour lui.',
 'La seconde moitié rejoue la première, avec une autre femme.'],
 'L’effet de vertige a été obtenu en filmant une maquette d’escalier posée à plat, faute de pouvoir déplacer une caméra dans un vrai clocher.'],
['movie','Les Sept Samouraïs|Shichinin no samurai',1954,'Drame|Action|Aventure','Akira Kurosawa|Toshiro Mifune','Toho',207,[
 'Film japonais de 1954, plus de trois heures, en noir et blanc.',
 'Un village de paysans engage des guerriers désœuvrés pour repousser des bandits.',
 'Sa structure — recruter une équipe, puis livrer bataille — a été copiée partout.',
 'Il a été refait en western américain six ans plus tard.',
 'Le combat final se déroule sous une pluie battante, dans la boue.'],
 'Le film a coûté si cher que le studio a interrompu la production deux fois. Kurosawa savait qu’on ne pouvait pas l’arrêter à mi-chemin, et en jouait.'],
['movie','Fargo',1996,'Crime|Drame|Thriller','Joel Coen|Ethan Coen|Frances McDormand','Gramercy Pictures',98,[
 'Film américain de 1996, dans la neige du Minnesota.',
 'Un concessionnaire automobile fait enlever sa propre femme pour toucher la rançon.',
 'Le générique prétend qu’il s’agit d’une histoire vraie ; c’est faux.',
 'Une policière enceinte mène l’enquête avec un calme imperturbable.',
 'Une broyeuse à bois clôt l’affaire de façon mémorable.'],
 'La mention « d’après une histoire vraie » était un pur artifice de mise en scène. Une Japonaise est morte en 2001 en cherchant la rançon enterrée du film.'],
['movie','The Big Lebowski',1998,'Comédie|Crime','Joel Coen|Ethan Coen|Jeff Bridges','Gramercy Pictures',117,[
 'Comédie américaine de 1998, échec en salles devenue culte absolu.',
 'Los Angeles, un tapis souillé, une confusion d’identité, beaucoup de bowling.',
 'Réalisée par les mêmes frères que Fargo, deux ans plus tard.',
 'Le héros ne travaille pas, boit des cocktails à la crème et porte un peignoir.',
 'Un festival annuel réunit des milliers de fans déguisés depuis 2002.'],
 'Le personnage est inspiré d’un vrai producteur, Jeff Dowd, militant des années 1960 qui buvait effectivement des White Russians.'],
['movie','Le Loup de Wall Street|The Wolf of Wall Street',2013,'Crime|Comédie|Drame','Martin Scorsese|Leonardo DiCaprio|Jonah Hill','Paramount',180,[
 'Film américain de 2013, trois heures, rythme frénétique.',
 'L’ascension et la chute d’un courtier de Long Island dans les années 1990.',
 'Cinquième collaboration entre le réalisateur et son acteur principal.',
 'Adapté des mémoires de l’escroc lui-même, qui apparaît dans le film.',
 'Une scène de paralysie sous sédatifs se joue en pure comédie physique.'],
 'Le vrai courtier apparaît à la dernière scène, présentant le personnage qui l’incarne. Il rembourse encore ses victimes sur ses droits d’auteur.'],
['movie','Django Unchained',2012,'Western|Drame','Quentin Tarantino|Jamie Foxx|Christoph Waltz','The Weinstein Company',165,[
 'Western américain de 2012, situé deux ans avant la guerre de Sécession.',
 'Un esclave affranchi devient chasseur de primes pour retrouver sa femme.',
 'Le réalisateur a obtenu son second Oscar du scénario avec ce film.',
 'Christoph Waltz y joue un dentiste allemand devenu chasseur de primes.',
 'Le titre reprend celui d’un western italien de 1966, dont l’acteur original fait un caméo.'],
 'Leonardo DiCaprio s’est coupé la main sur un verre brisé en pleine scène. Il a continué à jouer, et la prise a été conservée au montage.'],
['movie','Eternal Sunshine of the Spotless Mind|Du soleil plein la tête',2004,'Romance|Science-Fiction|Drame','Michel Gondry|Charlie Kaufman|Jim Carrey','Focus Features',108,[
 'Film américain de 2004, réalisé par un Français, écrit par un scénariste new-yorkais.',
 'Une clinique propose d’effacer les souvenirs d’une relation ratée.',
 'Le film se déroule à l’envers, à l’intérieur d’un cerveau en cours d’effacement.',
 'Jim Carrey y tient son rôle le plus retenu.',
 'Les effets ont été obtenus en caméra, par jeux de perspective plutôt qu’en numérique.'],
 'Le titre est un vers d’un poème d’Alexander Pope de 1717, cité dans le film par un personnage secondaire.'],
['movie','Her',2013,'Romance|Science-Fiction|Drame','Spike Jonze|Joaquin Phoenix|Scarlett Johansson','Warner Bros.',126,[
 'Film américain de 2013, dans un futur proche aux couleurs chaudes.',
 'Un homme qui écrit des lettres intimes pour les autres tombe amoureux d’un système d’exploitation.',
 'Le réalisateur a obtenu l’Oscar du meilleur scénario original.',
 'Le film a été tourné en partie à Shanghai pour figurer Los Angeles.',
 'La voix féminine du système n’a jamais de corps.'],
 'Samantha était d’abord interprétée par une autre actrice, dont toutes les prises ont été refaites après le tournage avec Scarlett Johansson.'],
['movie','Ex Machina',2014,'Science-Fiction|Drame|Thriller','Alex Garland|Alicia Vikander|Oscar Isaac','A24',108,[
 'Film britannique de 2014, quasiment un huis clos à trois personnages.',
 'Un programmeur est invité dans la résidence isolée du patron de son entreprise.',
 'Premier long métrage comme réalisateur d’un romancier et scénariste anglais.',
 'Il a obtenu l’Oscar des effets visuels contre des blockbusters au budget cent fois supérieur.',
 'Une scène de danse disco interrompt brutalement la tension.'],
 'L’équipe des effets comptait une trentaine de personnes contre plusieurs centaines chez ses concurrents aux Oscars, qu’elle a battus.'],
['movie','Le Labyrinthe de Pan|El laberinto del fauno',2006,'Fantastique|Drame|Guerre','Guillermo del Toro|Doug Jones|Javier Navarrete','Estudios Picasso',118,[
 'Film hispano-mexicain de 2006, conte cruel sur fond de guerre.',
 'L’Espagne franquiste de 1944, une fillette, un capitaine sadique, un labyrinthe.',
 'Le réalisateur a investi son propre salaire pour finir le film.',
 'Le faune et l’Homme pâle sont joués par le même acteur en prothèses.',
 'Une créature aux yeux dans les paumes garde un festin auquel il ne faut pas toucher.'],
 'Del Toro a renoncé à son salaire entier pour préserver son montage final, ce qu’il a également fait sur d’autres films.'],
['tv','Friends',1994,'Comédie',' Marta Kauffman|David Crane|Jennifer Aniston','NBC',10,[
 'Sitcom américaine lancée en 1994, dix saisons.',
 'Six amis new-yorkais, deux appartements et un café.',
 'Diffusée sur une grande chaîne hertzienne américaine, devant public.',
 'Les six acteurs ont négocié collectivement leurs salaires, cas unique à l’époque.',
 'Un canapé du café leur est mystérieusement toujours réservé.'],
 'Les acteurs négociaient tous ensemble et refusaient toute augmentation individuelle. Ils ont fini à un million de dollars par épisode chacun.'],
['tv','The Office',2005,'Comédie','Greg Daniels|Steve Carell|Rainn Wilson','NBC',9,[
 'Sitcom américaine lancée en 2005, filmée en faux documentaire.',
 'Une filiale de vente de papier en Pennsylvanie, dirigée par un patron insupportable.',
 'Adaptée d’une série britannique de Ricky Gervais.',
 'La première saison, très proche de l’original, a failli faire annuler la série.',
 'Les personnages regardent parfois la caméra, seuls témoins de l’absurdité.'],
 'La série a été sauvée par les ventes de téléchargements sur iTunes, argument inédit à l’époque pour convaincre une chaîne de renouveler.'],
['tv','Sherlock',2010,'Crime|Drame|Mystère','Mark Gatiss|Steven Moffat|Benedict Cumberbatch','BBC',4,[
 'Série britannique lancée en 2010, épisodes de quatre-vingt-dix minutes.',
 'Un détective consultant à Londres, mais avec un téléphone et un blog.',
 'Diffusée par le service public britannique, trois épisodes par saison.',
 'Les déductions du héros s’affichent en texte à l’écran.',
 'Son colocataire est un ancien médecin militaire revenu d’Afghanistan.'],
 'Le retour d’Afghanistan du docteur Watson figure déjà dans le roman de 1887 : le détail n’a eu besoin d’aucune actualisation.'],
['tv','Better Call Saul',2015,'Crime|Drame','Vince Gilligan|Peter Gould|Bob Odenkirk','AMC',6,[
 'Série américaine lancée en 2015, préquelle d’une autre série du même créateur.',
 'Un avocat besogneux d’Albuquerque glisse lentement vers la combine.',
 'Elle se déroule six ans avant les événements de la série mère.',
 'Le personnage principal n’était au départ qu’un second rôle comique.',
 'La photographie soigne les plans de parkings et de néons plus que les visages.'],
 'Conçue comme une comédie d’une demi-heure, elle est devenue un drame que beaucoup jugent supérieur à la série dont elle découle.'],
['tv','Mr. Robot',2015,'Drame|Crime','Sam Esmail|Rami Malek','USA Network',4,[
 'Série américaine lancée en 2015, quatre saisons.',
 'Un ingénieur en cybersécurité, hacker la nuit, veut effacer la dette mondiale.',
 'Le créateur a réalisé lui-même l’intégralité des trois dernières saisons.',
 'Les personnages sont souvent cadrés dans les coins de l’image, à contre-courant des règles.',
 'Le protagoniste s’adresse directement au spectateur, qu’il appelle son ami.'],
 'Les scènes de piratage sont techniquement exactes : la production employait des consultants pour que chaque commande à l’écran fonctionne réellement.'],
['tv','Westworld',2016,'Sci-Fi & Fantasy|Mystère|Drame','Jonathan Nolan|Lisa Joy|Anthony Hopkins','HBO',4,[
 'Série américaine lancée en 2016, adaptée d’un film de 1973.',
 'Un parc d’attractions western peuplé d’androïdes que les clients peuvent maltraiter.',
 'Le film d’origine avait été écrit et réalisé par Michael Crichton.',
 'Une reprise au piano mécanique de morceaux rock ponctue chaque épisode.',
 'Les hôtes répètent chaque jour le même scénario, jusqu’à ce que certains se souviennent.'],
 'Le film de 1973 contient la première utilisation d’images numériques dans un long métrage : la vision pixelisée de l’androïde.'],
['tv','The Mandalorian',2019,'Sci-Fi & Fantasy|Action & Adventure','Jon Favreau|Pedro Pascal','Disney+',3,[
 'Série américaine lancée en 2019, première série en prises de vue réelles de son univers.',
 'Un chasseur de primes masqué escorte un enfant très recherché.',
 'Tournée devant un mur d’écrans LED plutôt que sur fond vert.',
 'Le visage du héros reste caché presque tout du long.',
 'Un enfant vert aux longues oreilles a envahi Internet en quelques jours.'],
 'Le mur LED, appelé Volume, projette des décors en temps réel qui réagissent aux mouvements de caméra : les acteurs voient enfin ce qu’ils jouent.'],
['tv','Severance',2022,'Drame|Mystère|Sci-Fi & Fantasy','Dan Erickson|Ben Stiller|Adam Scott','Apple TV+',2,[
 'Série américaine lancée en 2022, esthétique de bureau glaçante.',
 'Une entreprise propose de séparer chirurgicalement les souvenirs du travail et ceux du privé.',
 'Réalisée en grande partie par un acteur comique reconverti.',
 'Les couloirs blancs interminables sont tournés dans un ancien siège de laboratoire.',
 'Les employés trient des nombres à l’écran sans savoir ce qu’ils signifient.'],
 'Le décor de bureau a été construit dans les anciens locaux des laboratoires Bell, dont l’architecture brutaliste servait déjà à filmer le futur dans les années 1970.'],
['tv','The Last of Us',2023,'Drame|Sci-Fi & Fantasy','Craig Mazin|Neil Druckmann|Pedro Pascal','HBO',2,[
 'Série américaine lancée en 2023, adaptée d’un jeu vidéo de 2013.',
 'Une pandémie fongique a effondré la civilisation ; un contrebandier convoie une adolescente.',
 'Coécrite par le créateur du jeu et par l’auteur de Chernobyl.',
 'Le troisième épisode s’écarte entièrement du jeu pour raconter une histoire inédite.',
 'Les infectés sont liés entre eux par un réseau souterrain de filaments.'],
 'Le troisième épisode, absent du jeu, est devenu l’un des plus commentés de l’histoire récente de la chaîne — et le plus détesté des joueurs les plus rigides.'],
['tv','Fargo',2014,'Crime|Drame|Comédie','Noah Hawley|Billy Bob Thornton','FX',5,[
 'Série américaine lancée en 2014, anthologie à distribution renouvelée.',
 'Chaque saison raconte un crime différent dans le Midwest enneigé.',
 'Elle partage son titre et son ton avec un film de 1996 des frères Coen.',
 'Les saisons se déroulent à des époques différentes, de 1950 à 2019.',
 'Chaque épisode s’ouvre sur la même affirmation mensongère d’authenticité.'],
 'Les frères Coen sont crédités comme producteurs mais n’ont jamais lu un seul scénario de la série, qu’ils ont laissée entièrement libre.'],
['tv','Twin Peaks',1990,'Drame|Mystère|Crime','David Lynch|Mark Frost|Kyle MacLachlan','ABC',3,[
 'Série américaine lancée en 1990, revenue vingt-cinq ans plus tard.',
 'Une petite ville de l’État de Washington, une lycéenne retrouvée morte, emballée dans du plastique.',
 'Cocréée par un cinéaste connu pour Eraserhead et Blue Velvet.',
 'Un agent du FBI dicte ses notes à une secrétaire qu’on ne voit jamais.',
 'Une pièce aux rideaux rouges et au sol en zigzag revient dans les rêves.'],
 'La chaîne a exigé qu’on révèle l’assassin à mi-parcours. Lynch était contre et a considéré que la série en était morte sur le coup.'],
['tv','X-Files : Aux frontières du réel|The X-Files',1993,'Sci-Fi & Fantasy|Drame|Mystère','Chris Carter|David Duchovny|Gillian Anderson','FOX',11,[
 'Série américaine lancée en 1993, onze saisons sur vingt-cinq ans.',
 'Deux agents du FBI enquêtent sur des affaires classées inexplicables.',
 'Elle alterne épisodes de mythologie et affaires isolées.',
 'La chaîne ne voulait pas de l’actrice principale, jugée trop peu glamour.',
 'Une affiche dans le bureau affirme vouloir croire.'],
 'Gillian Anderson était payée bien moins que son partenaire et n’avait pas le droit de se tenir à ses côtés à l’écran, seulement derrière lui. Il a fallu des saisons pour changer cela.'],
['tv','Lost : Les Disparus|Lost',2004,'Drame|Mystère|Sci-Fi & Fantasy','J. J. Abrams|Damon Lindelof|Carlton Cuse','ABC',6,[
 'Série américaine lancée en 2004, six saisons.',
 'Les survivants d’un crash d’avion sur une île qui n’est pas ce qu’elle paraît.',
 'Le pilote fut à l’époque le plus cher jamais produit pour une série.',
 'Chaque épisode alterne l’île et le passé d’un personnage.',
 'Une suite de nombres doit être saisie toutes les cent huit minutes.'],
 'Les scénaristes ont admis avoir improvisé une grande partie des mystères, et ont obtenu de la chaîne une date de fin pour pouvoir enfin en écrire une.'],
['tv','Rick et Morty|Rick and Morty',2013,'Animation|Comédie|Sci-Fi & Fantasy','Justin Roiland|Dan Harmon','Adult Swim',7,[
 'Série d’animation américaine lancée en 2013, pour adultes.',
 'Un savant alcoolique traîne son petit-fils à travers les dimensions.',
 'Née d’une parodie courte de Retour vers le futur.',
 'Son cocréateur est aussi l’auteur de la sitcom Community.',
 'Un pistolet à portails permet de fuir n’importe quelle réalité, y compris la sienne.'],
 'Une opération marketing autour d’une sauce de fast-food a provoqué des émeutes dans des restaurants américains en 2017.'],
['tv','BoJack Horseman',2014,'Animation|Comédie|Drame','Raphael Bob-Waksberg|Will Arnett','Netflix',6,[
 'Série d’animation américaine lancée en 2014, six saisons.',
 'Un ancien acteur de sitcom déprimé, dans un Hollywood peuplé d’animaux anthropomorphes.',
 'La première saison a été jugée médiocre avant que la série ne devienne l’une des plus sombres du médium.',
 'Les arrière-plans regorgent de jeux visuels sur les animaux.',
 'Le héros est un cheval qui parle et qui boit trop.'],
 'Un épisode entier est presque muet, un autre est un monologue funèbre de vingt minutes : la série a régulièrement cassé son propre format.'],
['tv','Arcane',2021,'Animation|Sci-Fi & Fantasy|Drame','Christian Linke|Alex Yee|Fortiche','Netflix',2,[
 'Série d’animation française lancée en 2021, tirée d’un jeu vidéo.',
 'Deux sœurs séparées entre une cité haute prospère et un sous-sol misérable.',
 'Animée par un studio parisien mêlant 3D et peinture 2D.',
 'Tirée de l’univers d’un jeu compétitif en ligne massivement joué.',
 'Une invention magique et industrielle divise la ville en deux camps.'],
 'Le studio d’animation est français et la série a été produite pendant six ans, budget largement supérieur aux standards de l’animation télévisée.'],
['tv','Death Note',2006,'Animation|Mystère|Drame','Tsugumi Ohba|Takeshi Obata|Madhouse','Nippon TV',1,[
 'Anime japonais de 2006, trente-sept épisodes, adapté d’un manga.',
 'Un lycéen surdoué trouve un carnet qui tue quiconque y voit son nom écrit.',
 'Un dieu de la mort désœuvré observe et mange des pommes.',
 'Le récit devient un duel de déduction entre le tueur et un détective anonyme.',
 'Une scène de dégustation de chips dissimule un ordinateur portable miniature.'],
 'Le manga a été interdit dans plusieurs pays après que des élèves ont recopié des noms de camarades dans des cahiers imités du modèle.'],
['tv','Cowboy Bebop',1998,'Animation|Action & Adventure|Sci-Fi & Fantasy','Shinichiro Watanabe|Yoko Kanno','Sunrise',1,[
 'Anime japonais de 1998, vingt-six épisodes, western spatial jazz.',
 'Des chasseurs de primes fauchés naviguent entre les colonies du système solaire.',
 'Sa musique big band est composée par Yoko Kanno.',
 'Chaque épisode porte un titre emprunté au vocabulaire musical.',
 'Le vaisseau porte le nom d’un genre musical né dans les années 1940.'],
 'La série a fait connaître l’animation japonaise à toute une génération d’Américains via une diffusion nocturne sur une chaîne câblée.'],
['tv','Kaamelott',2005,'Comédie|Drame','Alexandre Astier|Franck Pitiot','M6',6,[
 'Série française lancée en 2005, d’abord en épisodes de trois minutes.',
 'La légende arthurienne traitée en comédie de bureau, puis en tragédie.',
 'Écrite, réalisée, composée et interprétée par la même personne.',
 'Les six livres passent progressivement du format court au format long.',
 'Un roi désabusé règne sur une table ronde d’incompétents.'],
 'Le format s’allonge livre après livre jusqu’à devenir un drame : la chaîne a fini par ne plus savoir où le programmer.'],
['tv','Succession',2018,'Drame|Comédie','Jesse Armstrong|Brian Cox|Jeremy Strong','HBO',4,[
 'Série américaine lancée en 2018, quatre saisons.',
 'Les enfants d’un magnat des médias se disputent un empire que le père refuse de lâcher.',
 'Créée par un scénariste britannique venu de la comédie satirique.',
 'La caméra à l’épaule filme les dialogues comme un documentaire animalier.',
 'Le thème au piano est devenu instantanément reconnaissable.'],
 'Les acteurs recevaient parfois plusieurs versions d’une même scène et ne savaient pas laquelle serait tournée, pour préserver la tension.']
];
