/* Anecdotes rattachées aux 57 journées d'origine (clé = titre principal). */
export const TRIVIA = {
'Fight Club': 'Fincher a glissé quatre apparitions subliminales de Tyler avant sa première scène officielle. Le film fut un échec en salles avant de renaître en DVD.',
'Matrix': 'Will Smith a refusé le rôle de Neo pour tourner Wild Wild West. Il a reconnu depuis qu’il aurait « gâché » le film.',
'Interstellar': 'Les images du trou noir ont été calculées d’après les équations du physicien Kip Thorne, et ont donné lieu à de vraies publications scientifiques.',
'Inception': 'Le couloir en rotation n’est pas un effet numérique : une structure de trente mètres a été construite et mise à tourner sur son axe, avec les acteurs dedans.',
'Le Parrain': 'Le studio ne voulait ni de Brando ni de Pacino. Coppola a risqué son renvoi plusieurs fois pour les imposer.',
'Blade Runner': 'Le monologue final a été raccourci et réécrit par Rutger Hauer lui-même, la veille du tournage.',
'Pulp Fiction': 'Le contenu de la mallette n’est jamais montré. Tarantino a toujours refusé de l’expliquer : il n’y a rien à expliquer.',
'Les Évadés': 'Échec commercial complet à sa sortie. Ce sont les locations vidéo et les rediffusions télé qui en ont fait un classique.',
'Seven': 'Brad Pitt s’est vraiment blessé la main pendant une poursuite sous la pluie. La blessure a été écrite dans le scénario.',
'Alien': 'Pour la scène du dîner, l’équipe savait qu’il se passerait quelque chose, mais pas la quantité de sang. Les réactions sont authentiques.',
'Retour vers le futur': 'Eric Stoltz a tourné cinq semaines dans le rôle principal avant d’être remplacé par Michael J. Fox, qui tournait sa série le jour.',
'Le Silence des agneaux': 'Anthony Hopkins n’apparaît qu’environ seize minutes à l’écran, et a pourtant obtenu l’Oscar du meilleur acteur.',
'Jurassic Park': 'Le tremblement du verre d’eau a été obtenu en pinçant une corde de guitare fixée sous le tableau de bord.',
'Titanic': 'Les mains qui dessinent le portrait de Rose sont celles de James Cameron, gaucher, filmées puis inversées.',
'Le Seigneur des anneaux : La Communauté de l’anneau': 'Les trois films ont été tournés d’un seul bloc, en 438 jours consécutifs en Nouvelle-Zélande.',
'Le Fabuleux Destin d’Amélie Poulain': 'Le rôle avait été écrit pour Emily Watson. Son renoncement a poussé Jeunet à réécrire le film en français.',
'Parasite': 'La villa moderne n’existe pas : c’est un décor construit en extérieur, dont chaque niveau matérialise une strate sociale.',
'Mad Max: Fury Road': 'Le scénario a d’abord été dessiné sous forme de 3 500 planches, avant d’être écrit. Le film est resté seize ans en développement.',
'Le Voyage de Chihiro': 'Premier et longtemps seul film non anglophone à remporter l’Oscar du meilleur film d’animation.',
'Whiplash': 'Chazelle a d’abord tourné un court métrage de dix-huit minutes pour convaincre les financiers de lui confier le long.',
'Gladiator': 'Oliver Reed est mort pendant le tournage. Ses dernières scènes ont été achevées par un doublage numérique du visage.',
'Heat': 'Pacino et De Niro figuraient tous deux au générique du Parrain 2 sans jamais partager une scène. Ce café est leur première rencontre à l’écran.',
'Les Affranchis': 'La scène du « je te fais rire ? » vient d’un souvenir réel de Joe Pesci, improvisé puis intégré au scénario.',
'Shining': 'Stephen King déteste l’adaptation au point d’avoir produit sa propre version télévisée en 1997.',
'2001, l’Odyssée de l’espace': 'Kubrick a fait détruire décors et maquettes après le tournage, pour empêcher qu’on les réutilise dans d’autres films.',
'Terminator 2 : Le Jugement dernier': 'Avec près de cent millions de dollars, c’était le film le plus cher jamais produit à sa sortie.',
'Léon': 'Besson a écrit le scénario en un mois, pendant une interruption de la production du Cinquième Élément.',
'La Haine': 'Le film a été projeté au gouvernement français à la demande du Premier ministre de l’époque, Alain Juppé.',
'Intouchables': 'Inspiré de l’histoire vraie de Philippe Pozzo di Borgo et d’Abdel Sellou, déjà racontée dans un documentaire.',
'Premier Contact': 'Adapté d’une nouvelle de Ted Chiang, L’Histoire de ta vie, longtemps jugée inadaptable au cinéma.',
'Dune': 'Le roman avait déjà été porté à l’écran par David Lynch en 1984 — un film que Lynch a renié et refuse de commenter.',
'Joker': 'Joaquin Phoenix a travaillé le rire du personnage pendant des mois, en s’inspirant de vidéos de personnes atteintes de rire pathologique.',
'Get Out': 'Produit pour environ 4,5 millions de dollars, il en a rapporté plus de 250. Jordan Peele a obtenu l’Oscar du scénario.',
'La La Land': 'Annoncé par erreur meilleur film aux Oscars 2017, avant qu’on ne corrige en direct au profit de Moonlight.',
'Le Roi Lion': 'Considéré en interne comme le projet secondaire face à Pocahontas. Les meilleurs animateurs avaient été affectés à l’autre film.',
'Toy Story': 'Une première version, jugée trop cynique, a été rejetée par Disney. Pixar a tout réécrit en quelques mois pour éviter la fermeture.',
'WALL·E': 'La voix du robot a été conçue par Ben Burtt, déjà créateur des sons de R2-D2.',
'Old Boy': 'Choi Min-sik a réellement mangé quatre poulpes vivants pour une seule scène — il est bouddhiste et s’est excusé auprès des animaux.',
'Le Prestige': 'David Bowie avait d’abord refusé le rôle de Tesla. Nolan a pris l’avion pour aller le convaincre en personne.',
'Memento': 'Tourné en vingt-cinq jours. Le montage inversé était si déroutant qu’aucun grand studio n’a voulu le distribuer.',
'Trainspotting': 'Boyle a demandé aux acteurs de maigrir et de rencontrer d’anciens usagers d’un centre de soins d’Édimbourg.',
'Forrest Gump': 'Les scènes de foule comptent parmi les premières duplications numériques massives de figurants au cinéma.',
'Il faut sauver le soldat Ryan': 'Spielberg a imposé dix jours d’entraînement militaire à tous les acteurs sauf Matt Damon, pour que le ressentiment soit réel.',
'Le Cinquième Élément': 'Besson a écrit une première version de l’histoire à seize ans, au lycée.',
'Portrait de la jeune fille en feu': 'Les tableaux du film ont été peints par l’artiste Hélène Delmaire, dont les mains doublent celles de l’actrice.',
'Breaking Bad': 'La chaîne refusait Bryan Cranston, connu pour une sitcom. Gilligan a imposé son choix en montrant un épisode de X-Files qu’il avait écrit.',
'Game of Thrones': 'La série a été tournée dans dix pays, dont l’Islande pour le Nord et la Croatie pour Port-Réal.',
'The Wire': 'David Simon a passé une année entière au sein de la brigade criminelle de Baltimore avant d’écrire quoi que ce soit.',
'Les Soprano': 'James Gandolfini a partagé une part de son cachet avec le reste de la distribution lors d’une renégociation, seize mille dollars par acteur.',
'Stranger Things': 'La série devait s’appeler Montauk et se dérouler à Long Island. Quinze chaînes l’ont refusée avant Netflix.',
'Chernobyl': 'Le pont d’où les habitants ont regardé l’incendie est surnommé « pont de la mort », mais rien ne prouve qu’aucun spectateur n’ait survécu.',
'Dark': 'Première série originale de langue allemande de sa plateforme, pensée dès l’écriture pour être vue en version originale sous-titrée.',
'Le Bureau des légendes': 'Des anciens des services français ont été consultés tout au long de l’écriture, au point que la série sert de matériel pédagogique.',
'Peaky Blinders': 'Le gang a réellement existé à Birmingham à la fin du XIXᵉ siècle. Les lames dans les casquettes, en revanche, sont probablement une légende.',
'Black Mirror': 'Le titre désigne l’écran éteint d’un téléphone ou d’un téléviseur : ce rectangle noir dans lequel on se voit.',
'True Detective': 'Cary Fukunaga a réalisé seul les huit épisodes de la première saison, ce qui reste rare à la télévision américaine.',
'Squid Game': 'Le scénario a été refusé pendant plus de dix ans par les studios coréens, jugé trop violent et trop invraisemblable.',
};
